- .gitignore
- Gemfile
- Gemfile.lock
- Procfile
- lib/conditional_skylight.rb
- lib/travis/api/app/endpoint/builds.rb
- lib/travis/api/app/endpoint/jobs.rb
- lib/travis/api/workers/build_cancellation.rb
- lib/travis/api/workers/build_restart.rb
- lib/travis/api/workers/job_cancellation.rb
- lib/travis/api/workers/job_restart.rb
- lib/travis/sidekiq.rb
- spec/integration/v2/builds_spec.rb
- spec/integration/v2/jobs_spec.rb
These changes extract restarting and cancelling jobs and builds into sidekiq processes.
Specs have been updated and the changes have been tested on staging.travis-ci.org.
Everything is working fine.
@svenfuchs
> Ar cd background tasks

- lib/travis/api/app.rb
- lib/travis/api/app/error_handling.rb
- spec/integration/error_handling_spec.rb
add ErrorHandling class, refactor spec
correct the raven config class
correct the raven test
add a fake method for getting an exception
require error_handling
add new TestError class to test exceptions
add correct error class to test
add rescue block to raven send
make method a class method and add a test Travis.config.dns
add error the repos to test error
remove carla method in repos
add a fake error in repos
delete carla method
> add a new thread to send exception to sentry in purpose to speed up the api

- lib/travis/api/app/endpoint/repos.rb
- spec/integration/v2/repositories_spec.rb
> Allow branch names to contain slashes.

- lib/travis/api/v3.rb
- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/access_control/scoped.rb
- lib/travis/api/v3/access_control/user.rb
- lib/travis/api/v3/permissions.rb
- lib/travis/api/v3/permissions/generic.rb
- lib/travis/api/v3/permissions/repository.rb
- lib/travis/api/v3/renderer/model_renderer.rb
- lib/travis/api/v3/services/repository/disable.rb
- lib/travis/api/v3/services/repository/enable.rb
- lib/travis/api/v3/services/requests/create.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/owner/repositories_spec.rb
- spec/v3/services/repositories/for_current_user_spec.rb
- spec/v3/services/repository/find_spec.rb
- spec/v3/services/requests/create_spec.rb
> [WiP] v3: expose access permissions

- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/repositories/for_owner.rb
- spec/v3/services/repositories/for_owner_spec.rb
This will improve the service index and fix our documentation. See https://github.com/travis-pro/team-teal/issues/553
> API v3: owner/repos => repos/for_owner

- Gemfile
- Gemfile.lock
- lib/travis/api/app/endpoint/authorization.rb
This has been deployed on staging and is sending the data it needs to customer.io.
> Add check for first log in - send data to customer.io

- lib/travis/api/v3.rb
- lib/travis/api/v3/error.rb
- lib/travis/api/v3/router.rb
- spec/v3/error_handling_spec.rb
hey @rkh! Can you take a look at this?
> create MethodNotAllowed error

- Gemfile.lock
This updates travis-migrations as a new migration has been added: https://github.com/travis-ci/travis-migrations/commit/fcf6eea3e3122a7cbb857826db835de69974c54d
> bump travis-migrations

- lib/travis/api/v3/queries/repositories.rb
As noted by @rkh in the API introduction.
> Remove duplicated sorting configuration

- lib/travis/api/app/endpoint/requests.rb
- spec/integration/v2/requests_spec.rb
And returns service messages in case of error
> Fixes /requests endpoint

- lib/travis/api/app/endpoint/requests.rb
- spec/integration/v2/requests_spec.rb
Handle build and job restarts on POST request
> Handle build and job restarts on /requests

- Gemfile.lock
Getting at these: https://github.com/travis-ci/travis-core/pull/560
> Bump travis-core to get amqps fixes

- lib/travis/api/app/endpoint/requests.rb
- spec/integration/v2/requests_spec.rb
Restoring some code, that was probably removed on a merge
> Restoring /requests new version

- lib/travis/api/v3/renderer/log.rb
- lib/travis/api/v3/result.rb
> Try out a way of rendering plain text logs

- lib/travis/api/v3/queries/repository.rb
- lib/travis/api/v3/services/repository/enable.rb
- lib/travis/services/update_hook.rb
- spec/lib/services/update_hook_spec.rb
- spec/v3/services/repository/enable_spec.rb
Implements https://github.com/travis-pro/team-teal/issues/867
> Sync the repo on repo activate

- lib/travis/api/v3/queries/requests.rb
- lib/travis/api/v3/services/requests/create.rb
- spec/v3/services/requests/create_spec.rb
Implements https://github.com/travis-pro/team-teal/issues/864
> Include ratelimit info when rate limiting request creation

- lib/travis.rb
> Log setting up of module travis not travis core

- lib/travis/api/v3/models/user_settings.rb
- lib/travis/api/v3/queries/user_settings.rb
- spec/v3/services/user_settings/find_spec.rb
Re https://github.com/travis-pro/team-teal/issues/1433
> Add auto cancel repo settings

- lib/travis/api/v3/github.rb
- lib/travis/github/services/set_hook.rb
Re: https://github.com/travis-pro/team-teal/issues/1396
> Add more event types to repo hooks on github

- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/access_control/user.rb
- lib/travis/api/v3/permissions/generic.rb
- lib/travis/api/v3/permissions/repository.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/repositories/for_current_user_spec.rb
- spec/v3/services/repositories/for_owner_spec.rb
- spec/v3/services/repository/find_spec.rb
https://github.com/travis-pro/team-teal/issues/1408
> [API v3] Show if current user has admin rights on repository

- lib/travis/api/app/endpoint/repos.rb
- lib/travis/api/app/responders/image.rb
This PR is an extension of https://github.com/travis-ci/travis-api/pull/347
> Supply type hint to make image responder more specific

- lib/travis/api/app/services/schedule_cron_jobs.rb
Fixes https://github.com/travis-pro/team-teal/issues/1226
> Improve metrics for crons

- bin/cron
- lib/travis/api/app/schedulers/schedule_cron_jobs.rb
- spec/lib/schedulers/schedule_cron_jobs_spec.rb
Fixes https://github.com/travis-pro/team-teal/issues/1505
> Move crons scheduler to a scheduler diectory

- lib/travis/model/build.rb
- lib/travis/model/repository.rb
- spec/lib/model/repository/status_image_spec.rb
Should fix https://github.com/travis-pro/team-teal/issues/1554
Tests:
> Include crons when looking for builds ans states

- lib/travis/services/find_repo.rb
- lib/travis/services/find_repos.rb
- spec/integration/v2/repositories_spec.rb
- spec/integration/v2/requests_spec.rb
- spec/lib/services/find_branch_spec.rb
- spec/lib/services/find_branches_spec.rb
- spec/lib/services/find_builds_spec.rb
- spec/lib/services/find_caches_spec.rb
- spec/lib/services/find_repo_key_spec.rb
- spec/lib/services/find_repo_spec.rb
- spec/lib/services/find_repos_spec.rb
- spec/lib/services/find_requests_spec.rb
https://github.com/travis-pro/team-teal/issues/1596
> Hotfix, find_repo and find_repos shouldn't be scoped by current_user

- lib/travis/api/app/endpoint/repos.rb
- spec/integration/v2/repositories_spec.rb
https://github.com/travis-ci/travis-ci/issues/7137
> Remove current_user check from repos/:owner endpoint

- lib/travis/api/v3/models/build.rb
- lib/travis/api/v3/renderer/build.rb
- lib/travis/api/v3/renderer/job.rb
- spec/v3/services/active/for_owner_spec.rb
This adds a test for, and fixes the problem I was seeing on staging.
> the job needs to know what an active representation is as well as build

- lib/travis/api/v3/renderer/key_pair.rb
Need to add this to make the upcoming PR in developer work. Builds on #407.
> Add extra field to key_pair attributes

- lib/travis/api/v3/paginator.rb
- lib/travis/api/v3/services/requests/find.rb
This is tested on staging and working to fix the requests endpoint timeout (where it was calling to get all the requests for a repository without a limit).
> Requests fix

- lib/travis/api/app/endpoint/authorization.rb
From commit message: 
```
Some of our users report a problem with signing in and we're not really
sure what's causing it. This commit adds a few debug lines to see at
which point the handshake request fails.
```
> Add debug code to OAuth handshake

- lib/travis/api/v3/queries/request.rb
- spec/v3/services/requests/create_spec.rb
* Post it: https://github.com/travis-pro/post-its/issues/329
* Teal ticket: https://github.com/travis-pro/team-teal/issues/825
This should be deployed **after** the respective Gatekeeper request: https://github.com/travis-ci/travis-gatekeeper/pull/132
> Create a request record on POST to /requests

- Gemfile.lock
refs https://github.com/travis-pro/team-teal/issues/1775
> update travis-config dependency to include travis-ci/travis-config#14

- lib/travis/api/v3/queries/request.rb
- spec/v3/services/requests/create_spec.rb
This backports #424 for Enterprise 2.1
/cc @svenfuchs
> [Enterprise Backport] Create a request record on POST to /requests

- lib/travis/api/v3/renderer/beta_feature.rb
this updates the syntax in the renderer for beta_features. Tested on com-staging. (I'm not able to authenticate against org-staging at the moment so wasn't able to test there...)
> fix beta feature renderer

- lib/travis/api/v3/queries/cron.rb
- lib/travis/api/v3/services/cron/create.rb
- spec/v3/services/cron/create_spec.rb
This backports #432 for `enterprise-2.1`
/cc @carlad - mind checking this backport? There were a couple conflicts and want to make sure it looks right. Thanks so much!
> [Backport] add cron prefix to cron params

- lib/travis/model/env_helpers.rb
- spec/lib/model/job_spec.rb
Somehow one of these found its way into a .travis.yml.
https://sentry.io/travis-ci/org-api-production/issues/182903513/
> Handle nil secure env vars

- lib/travis/api/v3/queries/caches.rb
- lib/travis/api/v3/queries/log.rb
- lib/travis/api/v3/remote_query.rb
I need to rebase this for a master PR instead, but wanted to see the differences.
> Caches feedback

- lib/travis/api/app.rb
- lib/travis/api/app/endpoint/builds.rb
- lib/travis/api/app/endpoint/jobs.rb
- lib/travis/api/app/responders/json.rb
- lib/travis/api/serialize/v0/pusher/job.rb
- lib/travis/api/serialize/v2/http/build.rb
- lib/travis/api/serialize/v2/http/job.rb
- lib/travis/api/serialize/v2/http/jobs.rb
- lib/travis/api/serialize/v2/http/remote_log.rb
- lib/travis/api/v3/models/log.rb
- lib/travis/api/v3/queries/log.rb
- lib/travis/remote_log.rb
- spec/integration/v2/jobs_spec.rb
- spec/lib/travis/remote_log_spec.rb
- spec/unit/serialize/v2/http/job_spec.rb
- spec/unit/serialize/v2/http/jobs_spec.rb
- spec/v3/services/log/find_spec.rb
Reverts travis-ci/travis-api#457
> Revert "Ensure RemoteLog serializes more like direct database Log"

- Gemfile.lock
- lib/travis/api/serialize/v2/http/job.rb
- lib/travis/api/serialize/v2/http/jobs.rb
- lib/travis/api/v3/models/build.rb
- lib/travis/api/v3/models/job.rb
- lib/travis/api/v3/models/stage.rb
- lib/travis/api/v3/renderer/build.rb
- lib/travis/api/v3/renderer/job.rb
- lib/travis/api/v3/renderer/stage.rb
- lib/travis/testing/stubs.rb
- spec/unit/serialize/v2/http/job_spec.rb
- spec/unit/serialize/v2/http/jobs_spec.rb
- spec/v3/services/build/find_spec.rb
- spec/v3/services/builds/find_spec.rb
- spec/v3/services/job/find_spec.rb
- spec/v3/services/jobs/find_spec.rb
First stab at adding stages to the `/build[s]` and `/job[s]` payloads.
It does not add a first class `/stages` endpoint.
Ping @backspace :)
Do you think adding things to these payloads would be enough for Web? Would you need a `/stages` endpoint, too?
> Add stages to build[s] and job[s] payloads

- lib/travis/api/v3/models/build.rb
- lib/travis/api/v3/models/pull_request.rb
- lib/travis/api/v3/queries/requests.rb
- lib/travis/model.rb
- lib/travis/model/build.rb
- lib/travis/model/pull_request.rb
- lib/travis/model/request.rb
- lib/travis/model/request/pr.rb
- lib/travis/services/find_requests.rb
- spec/lib/model/request_spec.rb
Teal ticket: https://github.com/travis-pro/team-teal/issues/1345
> Stop reading request.payload, add a PullRequest model 

- lib/travis/api/v3/model_renderer.rb
- lib/travis/api/v3/service_index.rb
- spec/v3/service_index_spec.rb
This comments out `stage` to keep it dark.
> Hide stage resource from developer docs

- lib/travis/api/attack.rb
refs travis-pro/team-teal#1025
> rack/attack: remove feature flag on rack attack metrics, always enable instrumentation

- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/queries/request.rb
- lib/travis/api/v3/renderer/request.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/request/find.rb
- spec/v3/services/request/find_spec.rb
https://github.com/travis-pro/team-teal/issues/1987
> Add `/request/:id` endpoint

- Gemfile.lock
- lib/travis/api/v3/models/build.rb
- lib/travis/api/v3/queries/builds.rb
- lib/travis/api/v3/renderer/build.rb
- lib/travis/api/v3/services/builds/find.rb
- spec/v3/models/subscription_spec.rb
- spec/v3/services/build/find_spec.rb
- spec/v3/services/builds/find_spec.rb
This addresses this ticket: https://github.com/travis-pro/team-teal/issues/1996
API V3 developer docs have been updated (https://github.com/travis-pro/developer/pull/42). 
Visible here: https://developer-staging.travis-ci.org/resource/build#Build
Tests are passing on Travis and the changes have been deployed on org-staging, with the correct payload returned:
```
$ curl -H "Travis-API-Version: 3" -H "Authorization: token xxxx" https://api-taging.travis-ci.org/build/589426
{
"@type": "build",
"@href": "/build/589426",
"@representation": "standard",
"@permissions": {
"read": true,
"cancel": true,
"restart": true
},
"id": 589426,
"number": "400",
"state": "passed",
"duration": 0,
"event_type": "cron",
"previous_state": "errored",
"pull_request_title": null,
"pull_request_number": null, …
```
> Expose Build sender attributes as `created_by` 

- lib/travis/model/repository/settings.rb
https://github.com/travis-pro/team-teal/issues/2010
> Add defaults to auto_cancel settings in V2

- Gemfile
- Gemfile.lock
- lib/conditional_skylight.rb
refs https://github.com/travis-pro/team-teal/issues/2052
> evaluate skylight

- Gemfile.lock
- spec/integration/error_handling_spec.rb
This reverts commit b06fcb403fb4bb748aae1eb20fd07a49bfe9da50, reversing
changes made to 87060f7ba3b6c21c96faee2fb9c470a60996578a.
> Revert "Merge pull request #508 from travis-ci/igor-update-sentry-dep"

- lib/travis/api/enqueue/services/restart_model.rb
- lib/travis/api/v3/queries/build.rb
- lib/travis/api/v3/queries/job.rb
- lib/travis/api/v3/service.rb
- lib/travis/api/v3/services/build/restart.rb
- lib/travis/api/v3/services/job/restart.rb
- spec/v3/services/build/restart_spec.rb
- spec/v3/services/job/restart_spec.rb
Fixes https://github.com/travis-pro/team-teal/issues/2108
> Don't return 202 if request to restart was denied

- lib/travis/api/v3/service_index.rb
This won't change API endpoints in any way, but it will make a stage
resource show up in index.
> Add a stage resource

- lib/travis/api/app.rb
- lib/travis/api/app/middleware/honeycomb.rb
- lib/travis/api/app/middleware/request_id.rb
- lib/travis/honeycomb.rb
sample rpcs on a per-request basis, so we get closer to a full trace.
> honeycomb: allow for custom sampling that can be overridden per request

- lib/travis/api/app/middleware/honeycomb.rb
thanks @carlad for prompting this!
> honeycomb: track http referer in honeycomb

- lib/travis/api/v3/services/log/find.rb
- spec/v3/services/log/find_spec.rb
Logs for public repositories should be visible without a need to
authenticate, this commit enables this possibility.
> Allow to view public logs without authentication

- lib/travis/api/v3/models/user_settings.rb
- lib/travis/model/repository/settings.rb
- spec/v3/services/user_setting/find_spec.rb
See also https://github.com/travis-ci/travis-gatekeeper/pull/232
> Add env var switch for default auto cancel settings

- spec/v3/services/branches/find_spec.rb
Wrong repository was used for a query.
> Fix branches sorting spec

- lib/travis/api/app/base.rb
Enable logging and dumping errors in Enterprise for easier debugging
Backport of #589
> [Backport] Backport #589, enable logging and error dumping for Enterprise

- lib/travis/api/v3/renderer/job.rb
- spec/v3/services/job/find_spec.rb
- spec/v3/services/jobs/find_spec.rb
> expose created_at field for job in v3

- README.md
- lib/travis/api/v3/queries/enterprise_license.rb
- spec/v3/services/enterprise_license/find_spec.rb
This adds a check to make sure a User is not suspended when calculating active users.
> add suspended check to enterprise active users

- bin/suspend
- bin/unsuspend
- bin/user_mgmt.rb
- bin/users
```shell
./bin/suspend joecorcoran
./bin/unsuspend joecorcoran
./bin/users
./bin/users --suspended
./bin/users --active
./bin/users --inactive
```
> Add enterprise console commands suspend, unsuspend, and users

- lib/travis/api/app/endpoint/authorization.rb
> [Enterprise Backport] Revert "Fix SSL errors during Authorization against GitHub Enterprise with self signed cert" #664

- Aptfile
see also: https://medium.com/netflix-techblog/linux-performance-analysis-in-60-000-milliseconds-accc10403c55
refs travis-ci/reliability#25
> install sysstat package into api dynos for runtime analysis

- Aptfile
> install smem cli tool

- config/nginx.conf.erb
> enable keepalive for proxied connections in nginx

- Gemfile
- Gemfile.lock
> rbtrace gem for better runtime diagnostics

- Aptfile
refs refs travis-ci/reliability#25
> install vim for diagnostics

- Gemfile
- Gemfile.lock
- lib/travis/api/app.rb
> memory_profiler and allocation_tracer for runtime diagnostics

- Aptfile
> install htop for runtime diagnostics

- lib/travis/config/defaults.rb
- lib/travis/sidekiq.rb
> remove references to logs read replica (readonly database)

- lib/travis/api/v3/billing.rb
- lib/travis/api/v3/services/subscription/update_address.rb
- lib/travis/api/v3/services/subscription/update_creditcard.rb
- lib/travis/api/v3/services/subscriptions/create.rb
- spec/v3/billing_spec.rb
- spec/v3/services/subscription/update_address_spec.rb
- spec/v3/services/subscription/update_creditcard_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
This are a couple of mismatches we found with the current `billing-v2` API. (it's still work in progress but this works currently).
> Added nested key and corrected params for subscription

- lib/travis/api/v3/renderer/log.rb
Enterprise 2.2 backport for #692.
> [Backport] Check for Enterprise api endpoints before changing the raw_log_href (#692)

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/service.rb
- lib/travis/api/v3/services/subscription/cancel.rb
- lib/travis/api/v3/services/subscription/update_address.rb
- lib/travis/api/v3/services/subscription/update_creditcard.rb
- lib/travis/api/v3/services/subscriptions/create.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscription/cancel_spec.rb
- spec/v3/services/subscription/update_address_spec.rb
- spec/v3/services/subscription/update_creditcard_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
Properly handle all HTTP statuses and errors that the billing app returns.
> Handle errors and status codes from billing application

- lib/travis/api/v3/queries/subscriptions.rb
- lib/travis/api/v3/services/subscriptions/create.rb
- spec/v3/services/subscriptions/create_spec.rb
This PR changes the API to match what billing-v2 expects since travis-pro/billing-v2#47.
> Send CC Token on to create subscription

- lib/travis/api/serialize/v2/http/user.rb
- lib/travis/testing/stubs.rb
- spec/unit/endpoint/users_spec.rb
- spec/unit/serialize/v2/http/user_spec.rb
> Add user properties for Intercom

- lib/travis/api/v3/models/organization.rb
- lib/travis/api/v3/renderer/owner.rb
- spec/v3/services/installation/find_spec.rb
- spec/v3/services/organization/find_spec.rb
- spec/v3/services/organizations/for_current_user_spec.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/user/current_spec.rb
- spec/v3/services/user/find_spec.rb
Issue: https://github.com/travis-pro/billing-v2/issues/68
> Add education attribute to /owner /user /organization 

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/queries/subscription.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/subscription/update_plan.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscription/update_plan_spec.rb
I took Sergio's branch (https://github.com/travis-ci/travis-api/pull/743)  as base, to start working on this. Although I don't think I need it 😬
> Add  /update_plan endpoint

- bin/user_mgmt.rb
- bin/users
Backports #754 for `enterprise-2.2`
> [Backport] Update Travis Enterprise User Management to include counts and help (#754)

- lib/travis/api/app/endpoint/authorization.rb
this is a proposal to address travis-ci/travis-ci#5649.
> drop user agent check for /auth/github endpoint

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/queries/plans.rb
- lib/travis/api/v3/renderer/plan.rb
- lib/travis/api/v3/renderer/plans.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/plans/all.rb
- spec/support/billing_spec_helper.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/plans/all_spec.rb
Replaces #749, which was based on a reverted PR, causing conflicts and weirdness.
This is now based on #755, so:
* Don't merge this one before that one
* You probably only want to review 5d118a1
> Add GET /plans endpoint

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/queries/subscription.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/subscription/resubscribe.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscription/cancel_spec.rb
- spec/v3/services/subscription/resubscribe_spec.rb
> Add the resubscribe endpoint

- lib/travis/api/v3/queries/repositories.rb
- lib/travis/api/v3/services/repositories/for_current_user.rb
- lib/travis/api/v3/services/repositories/for_owner.rb
- spec/v3/services/repositories/filter_spec.rb
as per @backspace's request :)
> add experimental :name_filter to repositories services

- lib/travis/api/v3/models/billing_permissions.rb
- lib/travis/api/v3/models/owner.rb
- lib/travis/api/v3/models/subscription.rb
- lib/travis/api/v3/models/trial.rb
- lib/travis/api/v3/permissions/trial.rb
- lib/travis/api/v3/renderer/trial.rb
- spec/support/billing_spec_helper.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscriptions/all_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
- spec/v3/services/trials/all_spec.rb
Counterpart of travis-pro/billing-v2#108.
> Expose trials owner and permissions

- lib/travis/api/v3/models/request.rb
- lib/travis/api/v3/queries/requests.rb
- lib/travis/api/v3/renderer/request.rb
- spec/v3/services/request/find_spec.rb
This is part of the travis-yml project. Eventually we'll show this in the UI, near the parse messages.
https://github.com/orgs/travis-pro/projects/10
> Add yaml config to request

- lib/travis/api/v3/models/message.rb
- lib/travis/api/v3/queries/messages.rb
- spec/v3/services/messages/for_request_spec.rb
Matches ordering from https://github.com/travis-ci/travis-yml/pull/47
> Order messages by level, error first

- lib/travis/api/v3/github.rb
- lib/travis/github/services/set_hook.rb
https://sentry.io/travis-ci/org-api-production/issues/557739090/
www.traviscistatus.com/incidents/mhjxn1bnzdv8
> Remove membership event from set hook

- lib/travis/api/app/endpoint.rb
- lib/travis/api/app/endpoint/authorization.rb
- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/access_control/log_token.rb
- lib/travis/api/v3/renderer/log.rb
- lib/travis/api/v3/service.rb
- lib/travis/config/defaults.rb
- spec/unit/endpoint/authorization_spec.rb
- spec/unit/endpoint_spec.rb
- spec/v3/service_spec.rb
- spec/v3/services/log/find_spec.rb
This is a backport for `enterprise-2.2` of https://github.com/travis-ci/travis-api/pull/802
/cc @joecorcoran
> [Backport] Enforce authentication via setting (#802)

- lib/travis/api/v3/queries/email_subscription.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/email_subscription/resubscribe.rb
- spec/v3/services/email_subscription/resubscribe_spec.rb
```
POST /repo/123/email_subscription
204 No Content
```
Fixes https://github.com/travis-pro/team-teal/issues/2778
> Email resubscribe endpoint

- lib/travis/api/v3/models/user.rb
- lib/travis/api/v3/renderer/repository.rb
- spec/v3/services/repositories/for_current_user_spec.rb
Fixes https://github.com/travis-pro/team-teal/issues/2779
> Expose embedded optional attribute repository.email_subscribed

- lib/travis/api/app/endpoint/authorization.rb
- lib/travis/api/app/middleware/opencensus.rb
- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/gdpr_client.rb
- lib/travis/api/v3/models/import.rb
- lib/travis/api/v3/remote_query.rb
- lib/travis/api/v3/services/enterprise_license/find.rb
- lib/travis/remote_log.rb
- lib/travis/task.rb
refs travis-ci/reliability#160
> opencensus: faraday instrumentation (mostly for logs api)

- lib/travis/api/v3/models/json_sync.rb
- lib/travis/api/v3/models/user.rb
- lib/travis/api/v3/queries/preference.rb
- lib/travis/api/v3/queries/preferences.rb
- spec/v3/services/preference/find_spec.rb
- spec/v3/services/preference/update_spec.rb
- spec/v3/services/preferences/for_user_spec.rb
https://github.com/travis-pro/team-teal/issues/2793
It's not 100% clear to me why this solves the problem, but it does.
> Fix github oauth token override bug

- lib/travis/api/v3/services/repository/migrate.rb
- spec/v3/services/repository/migrate_spec.rb
@clekstro can you confirm what value we want for `force_reimport`?
> Emit a properly formated migration event to Kafka

- Gemfile
- Gemfile.lock
- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/extensions/preferences.rb
- lib/travis/api/v3/model.rb
- lib/travis/api/v3/models/json_slice.rb
- lib/travis/api/v3/models/json_sync.rb
- lib/travis/api/v3/models/organization.rb
- lib/travis/api/v3/models/organization_preferences.rb
- lib/travis/api/v3/models/preferences.rb
- lib/travis/api/v3/models/user.rb
- lib/travis/api/v3/models/user_preferences.rb
- lib/travis/api/v3/queries/preference.rb
- lib/travis/api/v3/queries/preferences.rb
- lib/travis/api/v3/renderer/preference.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/preference/for_organization.rb
- lib/travis/api/v3/services/preferences/for_organization.rb
- spec/v3/services/preference/find_spec.rb
- spec/v3/services/preference/for_organization_spec.rb
- spec/v3/services/preference/update_spec.rb
- spec/v3/services/preferences/for_organization_spec.rb
- spec/v3/services/preferences/for_user_spec.rb
> Read single organization preference

- Gemfile
- Gemfile.lock
- lib/travis/api/v3/access_control/generic.rb
- lib/travis/api/v3/extensions/preferences.rb
- lib/travis/api/v3/model.rb
- lib/travis/api/v3/models/json_slice.rb
- lib/travis/api/v3/models/json_sync.rb
- lib/travis/api/v3/models/organization.rb
- lib/travis/api/v3/models/organization_preferences.rb
- lib/travis/api/v3/models/preferences.rb
- lib/travis/api/v3/models/user.rb
- lib/travis/api/v3/models/user_preferences.rb
- lib/travis/api/v3/queries/preference.rb
- lib/travis/api/v3/queries/preferences.rb
- lib/travis/api/v3/renderer/preference.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/preference/for_organization.rb
- lib/travis/api/v3/services/preference/update.rb
- lib/travis/api/v3/services/preferences/for_organization.rb
- spec/v3/services/preference/find_spec.rb
- spec/v3/services/preference/for_organization_spec.rb
- spec/v3/services/preference/update_spec.rb
- spec/v3/services/preferences/for_organization_spec.rb
- spec/v3/services/preferences/for_user_spec.rb
Built on top of #872 and #873.
> Update organization preferences

- bin/migrate-hooks
- lib/travis/api/v3/github.rb
This also backports a separate change from `master` to include some GH client helper methods that are used by the migration.
> [BACKPORT] Add 'services to webhooks' migration

- lib/travis/api/v3/models/user_settings.rb
- lib/travis/api/v3/renderer/user_settings.rb
- lib/travis/model/repository/settings.rb
- spec/v3/services/user_settings/for_repository_spec.rb
https://github.com/orgs/travis-pro/projects/31
> Add allow config imports

- lib/travis/api/v3.rb
- lib/travis/api/v3/services/repository/activate.rb
- spec/v3/services/repository/activate_spec.rb
Reverts travis-ci/travis-api#917
> Revert "Enterprise backport #915 return 409 if repo ssh key is missing on repo activate"

- spec/v3/services/repository/activate_spec.rb
Backporting #915 in the Enterprise 2.2. branch
> Enterprise backport PR 915

- spec/v3/services/repository/activate_spec.rb
Reverts travis-ci/travis-api#920
> Revert "Enterprise backport PR 915"

- lib/travis/api/v3.rb
- lib/travis/api/v3/services/repository/activate.rb
- spec/v3/services/repository/activate_spec.rb
Correcting changes made to the previous backport so that functionality works as we want it to.
> Backport #915 into Enterprise 2.2 corrections

- .travis.yml
- lib/travis/api/v3/renderer/request.rb
- spec/v3/services/request/find_spec.rb
* We need it to display "draft" badge in UI
travis-ci/product#181
> Return pull_request_mergeable_state for request object

- lib/travis/api/app/endpoint.rb
- lib/travis/api/app/endpoint/repos.rb
- lib/travis/services/delete_caches.rb
- lib/travis/services/find_caches.rb
- spec/auth/v1/repos_spec.rb
- spec/auth/v2.1/repos_spec.rb
- spec/auth/v2/repos_spec.rb
- spec/lib/services/find_caches_spec.rb
- spec/unit/endpoint/repos_spec.rb
Closes https://github.com/travis-ci/bugs-questions-comments-ideas/issues/180
> Check for push permissions on caches page

- lib/travis/api/v3/services/caches/delete.rb
- lib/travis/api/v3/services/caches/find.rb
- spec/v3/services/caches/delete_spec.rb
- spec/v3/services/caches/find_spec.rb
Related travis-web PR: https://github.com/travis-ci/travis-web/pull/2065
https://github.com/travis-ci/bugs-questions-comments-ideas/issues/180
> Require login and push permission to access /caches

- Rakefile
It prevents from running `rake` in production because of [this](https://github.com/travis-ci/travis-api/pull/931/files#diff-52c976fc38ed2b4e3b1192f8a8e24cffL6) line
> Do not fetch DB schema everytime rake is executed

- lib/travis/api/v3/models/invoice.rb
- lib/travis/api/v3/renderer/invoice.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscription/invoices_spec.rb
(Requires https://github.com/travis-pro/billing-v2/pull/210 deployed before merging)
> Expose invoice amount_due

- lib/travis/api/v3/routes.rb
- spec/spec_helper.rb
(This is deployed since more than one year ago)
> Clean up feature flag no longer needed

- lib/travis/api/v3/services/subscription/resubscribe.rb
- spec/v3/services/subscription/resubscribe_spec.rb
To be deployed **after** https://github.com/travis-pro/billing-v2/pull/229.
> Expose resubscription status

- lib/travis/api/v3/models/subscription.rb
- lib/travis/api/v3/renderer/subscription.rb
- spec/v3/models/subscription_spec.rb
- spec/v3/services/subscriptions/all_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
> Present payment_intent to the client

- Gemfile
- Gemfile.lock
- lib/travis/api/v3/models/lead.rb
- lib/travis/api/v3/renderer/lead.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/lead/create.rb
- lib/travis/config/defaults.rb
- spec/v3/services/lead/create_spec.rb
This is essentially going to proxy a request to the Close API
> Add endpoint to create sales leads

- lib/travis/api/v3/models/build.rb
- lib/travis/api/v3/models/job.rb
- lib/travis/api/v3/renderer/build.rb
- lib/travis/api/v3/renderer/job.rb
- spec/v3/services/build/find_spec.rb
- spec/v3/services/job/find_spec.rb
* initial work for job.log_complete
* remove comments
* tidy up
* update model method, remove debug output
* add build spec, hide representations
* update build model
* refactor
* fix spec
* fix build find spec
* remove unnecesary representations, add available_attributes
(cherry picked from commit dde7f71)
>  [Backport] adding build and job log_complete param (#893)

- lib/travis/api/v3/config_obfuscator.rb
- spec/v3/config_obfuscator_spec.rb
> obfuscate env vars given as hashes

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/models/coupon.rb
- lib/travis/api/v3/queries/coupons.rb
- lib/travis/api/v3/renderer/coupon.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/coupons/find.rb
- spec/support/billing_spec_helper.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/coupons/find_spec.rb
- spec/v3/services/trials/all_spec.rb
https://github.com/travis-pro/billing-v2/issues/265
> Add coupon validation endpoint

- Gemfile
- Gemfile.lock
- lib/travis/api/app/endpoint/lint.rb
- lib/travis/api/v3/queries/lint.rb
- lib/travis/api/v3/renderer/lint.rb
- lib/travis/api/v3/services/lint/lint.rb
- lib/travis/config/defaults.rb
- spec/unit/endpoint/lint_spec.rb
- spec/v3/services/lint/lint_spec.rb
```
$ echo 'env: FOO=foo' > foo.yml
$ travis lint foo.yml --staging
Hooray, foo.yml looks valid :)
$ echo 'unknown: key' > foo.yml
$ travis lint foo.yml --staging
Warnings for foo.yml:
[x] [warn] on root: unknown key unknown (key)
```
> make /lint proxy travis-yml

- lib/travis/api/serialize/v2/http/user.rb
> LoginRequired exception in case of errors in User endpoint

- lib/travis/api/v3/models/ssl_key.rb
- lib/travis/model/ssl_key.rb
https://github.com/travis-ci/travis-ci/issues/5394
> Use `OpenSSL::PKey::RSA::PKCS1_OAEP_PADDING` for secrets

- lib/travis/api/v3/models/jobs_stats.rb
- lib/travis/api/v3/queries/jobs.rb
- lib/travis/api/v3/renderer/jobs_stats.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/queues/stats.rb
- spec/v3/services/queues/stats_spec.rb
We need to add an internal endpoint for jobs stats by queue
> Add jobs stats by queue

- lib/travis/api/v3.rb
- lib/travis/api/v3/services/repositories/for_current_user.rb
- lib/travis/api/v3/services/repositories/for_owner.rb
- spec/v3/services/repositories/filter_spec.rb
- spec/v3/services/repositories/for_current_user_spec.rb
- spec/v3/services/repositories/for_owner_spec.rb
Reverts travis-ci/travis-api#1002
> Revert "Raise exception  in case of missing installation instead a list of us…"

- lib/travis/api/v3/models/subscription.rb
- lib/travis/api/v3/renderer/subscription.rb
- spec/support/billing_spec_helper.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscriptions/all_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
For https://github.com/travis-pro/billing-v2/issues/373
> expose discount value to subscriptions

- lib/travis/api/v3/queries/builds.rb
- lib/travis/api/v3/queries/jobs.rb
- lib/travis/api/v3/query.rb
- lib/travis/config/defaults.rb
Some clients require more leniency when it comes to timeouts.
> Accommodate slower clients

- Dockerfile
Objective:
- Update bundler version.
> fix bundler issue in ship docker

- Dockerfile
Objective:
- ruby executable hook error on docker
ref: https://github.com/travis-ci/travis-api/pull/1048
> ruby_executable_hook error fix

- lib/travis/api/v3/renderer/user.rb
- spec/v3/services/installation/find_spec.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/user/current_spec.rb
- spec/v3/services/user/find_spec.rb
Required for https://travisci.assembla.com/spaces/Web/tickets/279/details
Related UI PR: https://github.com/travis-ci/travis-web/pull/2369
Intercom docs: https://www.intercom.com/help/en/articles/183-enable-identity-verification-for-web-and-mobile
> Add intercom secure hash to v3 user renderer

- lib/travis/api/v3/renderer/user.rb
- spec/v3/services/installation/find_spec.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/user/current_spec.rb
- spec/v3/services/user/find_spec.rb
Reverts travis-ci/travis-api#1055
> Revert "Add intercom secure hash to v3 user renderer"

- lib/travis/api/v3/renderer/user.rb
- spec/v3/services/installation/find_spec.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/user/current_spec.rb
- spec/v3/services/user/find_spec.rb
Fix of https://github.com/travis-ci/travis-api/pull/1055
> Add intercom secure hash v2

- lib/travis/api/attack.rb
Fix for https://travisci.assembla.com/spaces/VCS/tickets/136
> Increase POST requests throttling policy

- lib/travis/api/v3/queries/jobs.rb
This updates API to use the database functions added in https://github.com/travis-ci/travis-migrations/pull/222.
> Speed up jobs queries/endpoint

- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/queries/organization.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/organization/update_billing_permission.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/organization/update_billing_permission_spec.rb
This pull contains the new route, query and service related to the new feature introduced in billing-v2.
https://github.com/travis-pro/billing-v2/pull/538
> Billing Admin Only Security Settings

- bin/migrate-hooks
- lib/travis/api/v3/github.rb
corrected service hook check, skipping invalidated repos
> hooks migration script fixes

- .travis.yml
- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/models/allowance.rb
- lib/travis/api/v3/renderer/allowance.rb
- lib/travis/api/v3/renderer/owner.rb
- spec/v3/services/installation/find_spec.rb
- spec/v3/services/organization/find_spec.rb
- spec/v3/services/organizations/for_current_user_spec.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/user/current_spec.rb
- spec/v3/services/user/find_spec.rb
For security reasons visible only for logged in users.
> Allowance exposed in owner representation

- lib/travis/api/v3/models/subscription.rb
- lib/travis/api/v3/queries/subscriptions.rb
- lib/travis/api/v3/renderer/subscription.rb
- lib/travis/api/v3/services/subscription/update_address.rb
- lib/travis/api/v3/services/subscriptions/create.rb
- spec/support/billing_spec_helper.rb
- spec/v3/services/subscription/update_address_spec.rb
- spec/v3/services/subscriptions/all_spec.rb
- spec/v3/services/subscriptions/create_spec.rb
This PR contains the changes to allow customers from non EU contraries to provide vat details.
https://github.com/travis-pro/billing-v2/pull/597
> Support international vat

- lib/travis/api/v3/models/organization_preferences.rb
- lib/travis/api/v3/models/user_preferences.rb
- spec/v3/services/preferences/for_organization_spec.rb
- spec/v3/services/preferences/for_user_spec.rb
> OSS credit option on by default

- lib/travis/api/enqueue/services/restart_model.rb
- lib/travis/api/v3/queries/build_permissions.rb
- lib/travis/api/v3/renderer/execution_per_repo.rb
- lib/travis/api/v3/renderer/execution_per_sender.rb
- lib/travis/api/v3/renderer/executions_per_repo.rb
- lib/travis/api/v3/renderer/executions_per_sender.rb
- lib/travis/api/v3/renderer/user.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/executions/for_owner.rb
- lib/travis/api/v3/services/executions/for_owner_per_repo.rb
- lib/travis/api/v3/services/executions/for_owner_per_sender.rb
- spec/lib/travis/api/enqueue/services/restart_model_spec.rb
- spec/support/billing_spec_helper.rb
- spec/v3/queries/build_permissions_spec.rb
- spec/v3/services/v2_subscription/executions_spec.rb
> Billing milestone 2

- lib/travis/api/enqueue/services/restart_model.rb
- lib/travis/testing/factories.rb
- spec/lib/travis/api/enqueue/services/restart_model_spec.rb
- spec/v3/services/job/restart_spec.rb
Fix build restart subscription/plan check
> Fix build restart subscription/plan check

- lib/travis/api/enqueue/services/restart_model.rb
- lib/travis/model.rb
- lib/travis/model/organization.rb
- lib/travis/model/owner_group.rb
- lib/travis/model/user.rb
- spec/lib/travis/api/enqueue/services/restart_model_spec.rb
Added owner group model
Authorize build if owner belongs to a group
Added test case for this scenario
> Authorize build if owner belongs to a group

- lib/travis/api/v3/services/build_permissions/find_for_organization.rb
Removed pagination on manage users popup
> Removed pagination on manage users popup

- .travis.yml
- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/models/auto_refill.rb
- lib/travis/api/v3/models/v2_plan_config.rb
- lib/travis/api/v3/models/v2_subscription.rb
- lib/travis/api/v3/queries/v2_subscription.rb
- lib/travis/api/v3/renderer/auto_refill.rb
- lib/travis/api/v3/renderer/v2_subscription.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/v2_subscription/auto_refill.rb
- lib/travis/api/v3/services/v2_subscription/toggle_auto_refill.rb
- spec/v3/services/v2_subscriptions/all_spec.rb
- spec/v3/services/v2_subscriptions/create_spec.rb
> auto refill

- lib/travis/api/v3/models/executions.rb
- lib/travis/api/v3/models/invoice.rb
- lib/travis/api/v3/renderer/execution.rb
- lib/travis/api/v3/renderer/invoice.rb
- lib/travis/api/v3/services/executions/for_owner.rb
- lib/travis/services/find_caches.rb
- spec/lib/services/find_caches_spec.rb
- spec/v3/billing_client_spec.rb
- spec/v3/services/subscription/invoices_spec.rb
- spec/v3/services/v2_subscription/executions_spec.rb
- spec/v3/services/v2_subscription/invoices_spec.rb
> Bugfix cycle 5

- lib/travis/api/v3/insights_client.rb
- lib/travis/api/v3/models/insights_spotlight_summary.rb
- lib/travis/api/v3/queries/insights_spotlight_summary.rb
- lib/travis/api/v3/renderer/insights_spotlight_summary.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/insights_spotlight_summary/all.rb
Service creation for travis-api to fetch spotlight data from Insights API and database.
> travis-api service for spotlight summaries

- lib/travis/api/app/endpoint/setting_endpoint.rb
- lib/travis/api/v3/models/env_vars.rb
- lib/travis/api/v3/queries/env_var.rb
- lib/travis/api/v3/queries/env_vars.rb
- lib/travis/api/v3/services/env_var/delete.rb
- lib/travis/api/v3/services/env_var/update.rb
- lib/travis/api/v3/services/env_vars/create.rb
- spec/v3/services/env_var/delete_spec.rb
- spec/v3/services/env_var/update_spec.rb
- spec/v3/services/env_vars/create_spec.rb
https://travisci.assembla.com/spaces/Bugfix-Service/tickets/realtime_cardwall?ticket=181
> Bsfy 181 fix

- lib/travis/api/app/access_token.rb
- lib/travis/api/app/endpoint/authorization.rb
- lib/travis/api/app/endpoint/repos.rb
- lib/travis/model/token.rb
- lib/travis/model/user.rb
- spec/lib/model/user_spec.rb
- spec/unit/access_token_spec.rb
- spec/unit/endpoint/repos_spec.rb
> Use RSS token for builds atom feed

- lib/travis/api/app/endpoint/builds.rb
- lib/travis/api/v3/queries/build.rb
https://app.clickup.com/t/31pmbj0
> Add reason for manual cancel in build cancellation

- lib/travis/api/app/endpoint/builds.rb
- lib/travis/api/v3/queries/build.rb
Reverts travis-ci/travis-api#1262
> Revert "Add reason for manual cancel in build cancellation"

- lib/travis/api/app/endpoint/builds.rb
- lib/travis/api/v3/queries/build.rb
> Reopen: Add reason for manual cancel in build cancellation

- lib/travis/api/app/access_token.rb
- lib/travis/api/v3/queries/access_token.rb
- lib/travis/api/v3/renderer/access_token.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services.rb
- lib/travis/api/v3/services/access_token/regenerate_token.rb
- lib/travis/api/v3/services/access_token/remove_token.rb
- lib/travis/api/v3/services/job/debug.rb
- lib/travis/api/v3/services/v2_subscription/update_payment_details.rb
- spec/v3/services/access_token/regenerate_token_spec.rb
- spec/v3/services/access_token/remove_token_spec.rb
> Maintenance project Q2

- Gemfile
- Gemfile.lock
- lib/travis/api/v3/models/fingerprint.rb
- lib/travis/model/repository/settings.rb
- lib/travis/private_key.rb
- spec/integration/v2/settings/ssh_key_spec.rb
- spec/lib/model/repository/settings/ssh_key_spec.rb
- spec/v3/models/fingerprint_spec.rb
TBT-7 support for eddsa (#1321)
> Release 2024 05 22

- lib/travis/api/v3/models/custom_key.rb
- lib/travis/api/v3/queries/custom_key.rb
- lib/travis/api/v3/services/custom_keys/create.rb
- spec/v3/models/custom_key_spec.rb
Ticket: [TBT-29](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/29-cosign-requires-update-to-newer-version--rsa-keys-are-no-longer-accepted-/details) PR: https://github.com/travis-ci/travis-api/pull/1325
> Release 2024 06 11

- lib/travis/api/v3/authorizer.rb
- lib/travis/api/v3/collection_renderer.rb
- lib/travis/api/v3/query.rb
- lib/travis/api/v3/renderer/repositories.rb
- spec/v3/services/repositories/filter_spec.rb
- spec/v3/services/repositories/for_current_user_spec.rb
- spec/v3/services/repositories/for_owner_spec.rb
[TBT-94](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=94) query cache (#1328)
[TBT-95](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=95) authorizer repos cache (#1329)
> Release 2024 07 31

- lib/travis/api/v3/collection_renderer.rb
- lib/travis/api/v3/renderer/repository.rb
[TBT-96] - new representations for collections (#1334)
> Release 2024 08 19

- lib/travis/api/v3/renderer/job.rb
[TBT-80](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=80) - vm_size in jobs (#1337)
> Release 2024 09 02

- lib/travis/api/app/access_token.rb
- lib/travis/api/app/endpoint/authorization.rb
- lib/travis/api/v3/queries/access_token.rb
- lib/travis/api/v3/services/access_token/regenerate_token.rb
- lib/travis/config/defaults.rb
- lib/travis/model/token.rb
- lib/travis/model/user.rb
- spec/unit/access_token_spec.rb
- spec/v3/services/access_token/regenerate_token_spec.rb
- spec/v3/services/job/find_spec.rb
- spec/v3/services/jobs/find_spec.rb
[TBT-46](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=46) -  Handle new web token with expiry (#1340)
> Release 2024 10 24

- lib/travis/api/v3/models/v2_subscription.rb
- lib/travis/api/v3/renderer/v2_subscription.rb
- spec/v3/services/v2_subscriptions/all_spec.rb
- spec/v3/services/v2_subscriptions/create_spec.rb
[TBT-34](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=34) - add defer_pause to renderer and model (#1344)
> Release 24 11 27

- lib/travis/api/v3.rb
- lib/travis/api/v3/billing_client.rb
- spec/v3/billing_client_spec.rb
[TBT-220](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=220) Add cc timeout messsage (#1346)
> Release 24 12 11

- lib/travis/api/v3/renderer/repository.rb
- spec/v3/services/owner/find_spec.rb
- spec/v3/services/repositories/for_current_user_spec.rb
- spec/v3/services/repositories/for_owner_spec.rb
- spec/v3/services/repository/find_spec.rb
- spec/v3/services/v2_subscription/executions_spec.rb
[TBT-276](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=276)  - build count (#1357)
>  Release 2025.03.03

- lib/travis/api/app/middleware/opencensus.rb
TBT-319 Fix stackdriver error (#1361)
> Release 2025 03 26

- lib/travis/api/app/endpoint/authorization.rb
- lib/travis/api/v3/billing_client.rb
- lib/travis/api/v3/models/plan_share.rb
- lib/travis/api/v3/models/v2_subscription.rb
- lib/travis/api/v3/queries/v2_subscription.rb
- lib/travis/api/v3/renderer/plan_share.rb
- lib/travis/api/v3/renderer/plan_shares.rb
- lib/travis/api/v3/renderer/v2_subscription.rb
- lib/travis/api/v3/routes.rb
- lib/travis/api/v3/services/v2_subscription/share.rb
- spec/v3/services/v2_subscription/share_spec.rb
- spec/v3/services/v2_subscriptions/all_spec.rb
- spec/v3/services/v2_subscriptions/create_spec.rb
[TBT-300] plan share prd (#1362)
> Release 30 04 2025 

- lib/travis/api/v3/services/csv_exports/create.rb
[Tbt 394](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=394) - remove report_type from payload (#1379)
> Release 2025 07 09

- lib/travis/api/v3/models/v2_addon.rb
- lib/travis/api/v3/renderer/v2_addon.rb
- spec/support/billing_spec_helper.rb
- spec/v3/services/v2_subscriptions/all_spec.rb
- spec/v3/services/v2_subscriptions/create_spec.rb
[TBT-393](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=393) - update plan addons list on the UI (#1382)
> Release 2025 07 21

- lib/travis/api/v3/models/v2_subscription.rb
[TBT-378](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=378) Include expired addons in the plan (#1383)
> Release 2025 08 06
