travis-ci/travis-api

lib/travis/api/v3/access_control/anonymous.rb, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/access_control/user.rb, lib/travis/api/v3/extensions/belongs_to.rb, lib/travis/api/v3/queries/repositories.rb, lib/travis/api/v3/renderer.rb, lib/travis/api/v3/renderer/model_renderer.rb, lib/travis/api/v3/renderer/owner.rb, lib/travis/api/v3/result.rb, lib/travis/api/v3/router.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/service.rb, lib/travis/api/v3/services/owner/repositories.rb, spec/v3/extensions/belongs_to_spec.rb, spec/v3/result_spec.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/owner/repositories_spec.rb
Adds the following
* `/owner/:name/repos` - load the repo data for a GitHub account by login
* `/owner/:name?include=user.repositories,organization.repositories` or `/owner/:name?include=owner.repositories` - load user or org data including repositories by login
ping @lislis and @drogus
=> API v3: list repo by owner

Gemfile.lock, lib/travis/api/v2/http/build.rb, lib/travis/api/v2/http/builds.rb, spec/unit/api/v2/http/build_spec.rb, spec/unit/api/v2/http/builds_spec.rb
So that the proper build even_type for builds triggered via API can be displayed
/cc @drogus @rkh
=> Include event_type to build payloads

Gemfile.lock, travis-api.gemspec
> The pg gem prior to version 0.14.1 uses the method rb_thread_select. This method was removed in Ruby 2.2.
http://stackoverflow.com/questions/28062592/symbol-lookup-error-since-upgrading-to-ruby-2-2-0
=> Relax dependency for pg, remove thin

lib/travis/api/v2/http/repository.rb, spec/unit/api/v2/http/repository_spec.rb
Interestingly, it's already part of the repositories payload, just not of the repository payload in v2.
=> expose active flag in repo payload in v2

lib/travis/api/v3/models/branch.rb, lib/travis/api/v3/models/repository.rb
This fixes a bug where ids on the repository and branch models were not set correctly and causing postgres to, in rkh's words "freak out".
This has been tested on staging and all appears to be working.
=> v3 prefix ids with correct tables when ordering

Gemfile.lock, lib/travis/api/app.rb, lib/travis/api/attack.rb
Base throttling on access token if the call is authenticated, rather than on IP address, improve throttling rules.
Rules:
* Throttle unauthenticated calls to 50/min based on IP address.
* Throttle authenticated calls to 100/min based on access token (no more blocking in large offices).
* Ban clients for one hour if sending 10 or more POST requests to /auth/github within one minute. Ban unauthenticated calls based on IP address and authenticated calls based on access token.
* Ban clients manually with their IP address listed in the `api_blacklisted_ips` Redis set.
=> better request throttling and auto-banning

lib/travis/api/attack.rb
Following feedback from organization Sonarc Source, who monitor the status of each of their 94 apps twice per minute, we have increased the throttle limit for authenticated requests to accommodate their use case.
=> increase throttle limit for authenticated requests

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/permissions/build.rb, lib/travis/api/v3/permissions/job.rb, lib/travis/api/v3/queries/build.rb, lib/travis/api/v3/queries/job.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/build/cancel.rb, lib/travis/api/v3/services/build/restart.rb, lib/travis/api/v3/services/job/cancel.rb, lib/travis/api/v3/services/job/restart.rb, lib/travis/api/workers/job_restart.rb, spec/v3/services/build/cancel_spec.rb, spec/v3/services/build/find_spec.rb, spec/v3/services/build/restart_spec.rb, spec/v3/services/builds/find_spec.rb, spec/v3/services/job/cancel_spec.rb, spec/v3/services/job/find_spec.rb, spec/v3/services/job/restart_spec.rb
This PR adds endpoints for restarting and canceling builds and jobs:
`.../v3/build/[:id]/restart -- ../v3/build/[:id]/cancel`
`.../v3/job/[:id]/restart -- ../v3/job/[:id]/cancel`
These endpoints use the existing api sidekiq workers for the moment as it's anticipated that eventually the rewrite to `travis-hub` will process these requests.
Specs have been added to test the service sends the correct payload to the correct worker.
The changes have been deployed to staging.org and staging.com and tested manually there by restarting then cancelling both a build and a job and watching the change appear in travis-web on staging.org and staging.com.
=> v3 Add Build and Job Restart and Cancellation

Gemfile.lock, lib/travis/api/v3/query.rb, lib/travis/api/v3/renderer/collection_renderer.rb, spec/v3/services/repositories/for_current_user_spec.rb
Our db join optimisation and ActiveRecord don't like queries in the style of `/repos?include=user.repositories`, which also is a query that doesn't make a lot of sense (there repos can also be found at top level). However, such queries not having a good use case doesn't keep people from constructing them.
Therefore the logic is extended in the following way: If you already are rendering a collection of type *X*, do not allow eager loading a nested collection of the same type.
=> API v3: no list nesting

lib/travis/api/v3/queries/branches.rb, lib/travis/api/v3/queries/owner.rb, lib/travis/api/v3/query.rb, lib/travis/api/v3/service.rb, lib/travis/api/v3/services/branches/find.rb, spec/v3/services/branches/find_spec.rb
Adds sorting to branches API. `sort_by` query parameter can be used. Currently able to sort by `name` and `last_build`. Can be suffixed by `:desc` or `:asc` to change order, can be a comma separated list, ie, `?sort_by=name,last_build:desc` (`:desc` only applies to `last_build`).
Also sets default sorting for branches to `last_build:desc`.
See [queries/branches.rb](https://github.com/travis-ci/travis-api/blob/33d31131c1e13382ec12f036b16d24af540badba/lib/travis/api/v3/queries/branches.rb#L3-L4) for an example on how to add sorting to a query (make sure to also [call `sort`](https://github.com/travis-ci/travis-api/blob/33d31131c1e13382ec12f036b16d24af540badba/lib/travis/api/v3/queries/branches.rb#L7)).
This fixes https://github.com/travis-pro/team-teal/issues/507.
=> API v3: add ability to sort branches

lib/travis/api/v3/queries/branches.rb, lib/travis/api/v3/query.rb, lib/travis/api/v3/services/branches/find.rb, spec/v3/services/branches/find_spec.rb
* allow filtering branches via `?branch.exists_on_github=[true|false]`
* allow sorting branches by `exists_on_github`
* allow sorting branches by `default_branch`
* default sort for branches changed to `default_branch,exists_on_github,last_build`
This branch is currently deployed to staging.
=> better branches filtering and sorting

lib/travis/api/v3.rb, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/queries/user.rb, lib/travis/api/v3/query.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/user/sync.rb, spec/v3/services/user/sync_spec.rb
This adds an endpoint that allows a user to trigger a sync on their account.
The specs are passing locally and on Travis.
The changes have been deployed to org-staging and a post request sent to test the sidekiq process (which uses the `Travis::GitHubSync::Workers::SyncUser` class). Everything is working as it should.
=> v3 Add user/:id/sync endpoint

Gemfile, Gemfile.lock, lib/travis/api/app.rb, lib/travis/api/v3/metrics.rb, lib/travis/api/v3/router.rb, spec/spec_helper.rb, spec/v3/metrics_spec.rb
This adds proper per endpoint v3 metrics to librato. It will help us monitor what happens when we start switching web over to v3.
=> v3: add metrics

lib/travis/api/v3/queries/repositories.rb, spec/v3/services/repositories/for_owner_spec.rb
Right now it sorts by id. 
It could also sort by finished_at, which would change the behaviour for builds that haven't finished running.
We could also add both. What do you think @drogus?
To check what is returned use `... /repos?sort_by=default_branch.last_build`
This addresses this issue: https://github.com/travis-pro/team-teal/issues/732
=> Add ability to sort repos by default_branch.last_build

lib/travis/api/attack.rb
This is to prevent internal developers from being locked out by the rate limiting.
Tests passing locally and on travis-ci
=> Remove hard coded request path to allow whitelisted request paths

lib/travis/sidekiq.rb
```
Unicorn, which we use to serve the API, uses forked workers that need
only one connection per instance. Sidekiq on the other hand runs several
instances in memory, so it needs a higher concurrency setting. This
commit introduces a way to set sidekiq db pool using
SIDEKIQ_DB_POOL_SIZE
```
=> Allow to set sidekiq concurrency separately from web workers

lib/travis/api/app/extensions.rb
For not entirely 100% clear reasons this suddenly starts breaking in certain contexts (where `lib` is part of a parent directory on the matched path).
After debugging this with @tyranja and @drogus we've decided to unsmart this.
=> Unsmart loading app extensions

Rakefile
This fixes the problem where the Heroku deploy was failing because the `fail` condition for production was preventing rake from finding the tasks.
Tests are all passing and deployment to staging now works.
=> add better condition check for rake

lib/travis/api/v3/models/request.rb, lib/travis/api/v3/renderer/request.rb, spec/v3/services/requests/find_spec.rb
This adds a `branch_name` to the request payload.
It has been tested locally and on staging. 
All tests passing on Travis-CI.
=> V3 add branch_name for request

lib/travis/api/v3/queries/crons.rb
There's an issue where any error in the `start` method is not rescued, and will bubble up to the `start_all` method, causing all subsequent crons to be aborted.
This change has been deployed to staging and everything seems to be working.
=> add error rescue for cron start method

lib/travis/api/v3/queries/repositories.rb
Otherwise in some circumstances postgres may complain about
disambiguity.
=> Specify a table when sorting by current_build_id

lib/travis/api/v3/queries/repositories.rb
This a quick workaround for sorting by current_build. When the field
that we use to sort is the same as one of the associations name API V3
will try to join the association. So in this case it will try to join
:current_build, which fails. This needs a better solution, but I want to
get this working for now.
=> Rename current_build sort to current_build_id

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/models/settings.rb, lib/travis/api/v3/queries/settings.rb, lib/travis/api/v3/query.rb, lib/travis/api/v3/renderer/settings.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/routes/dsl.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/settings/find.rb, lib/travis/api/v3/services/settings/update.rb, spec/v3/services/settings_spec.rb
This adds `/repo/{repository.id}/settings` endpoints for reading
and updating repo settings.
Main points:
1. Sets up Settings as a first class resource instead of as an
attribute of Repository
2. Adds new meta-programmed method to Query for accessing all
prefixed params as a hash.
=> Add settings to API V3

lib/travis/api/v3/queries/repositories.rb, lib/travis/api/v3/query.rb, lib/travis/api/v3/renderer/model_renderer.rb, lib/travis/api/v3/renderer/repository.rb, lib/travis/api/v3/service_index.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/repositories/for_current_user_spec.rb, spec/v3/services/repositories/for_owner_spec.rb, spec/v3/services/repository/find_spec.rb
After talking with @rkh about changes in API we decided that it would be best to somehow mark `current_build` as experimental. This PR is a rough first try to do it and I'm submitting it for discussion. At the moment I'm just hiding all the things that are marked as experimental, but after thinking about this more I'm not sure that's the best way, because if we ever decide to write a client that would use index page, there would be no way to use experimental features.
Another way would be to either mark them experimental in the index or make it possible to fetch "regular" index and "experimental" index. I'm not really sure what would be best here.
Another thing is that there're no tests for most of the things added here. I could add tests for it in `spec/v3/service_index_spec.rb`, but …
=> More `current_build` work

lib/travis/api/attack.rb
Currently almost all calls against API are being rate limited, including build status images. This leads to common requesters such as GitHub's camo proxy to get rate limited and receive a 429 response code.
This patch attempts to allow those requests.
=> safelist build status image requests coming from github

lib/travis/api/attack.rb, spec/unit/attack_spec.rb
@renee-travisci and myself finally tracked this down.
We were getting 429 responses on GitHub. Upon further investigation, we determined that while some of the GitHub proxy requests have a `github-camo` user agent, this was not always the case. Some of them also had a user agent of `Go-http-client/1.1`, most likely an alternative to camo that github is testing.
By relaxing the restrictions on rate-limiting to always allow requests to build images, this should get rid of those 429 responses for good.
=> no longer test against user agent for github rate-limit, since it is not consistently github-camo

vendor/travis-core/lib/travis/event.rb
As discussed with @svenfuchs /cc @aakritigupta @anarosas
=> Add deprecation notice to Event.notify() that writes to log

lib/travis/api/app.rb
This PR Backports https://github.com/travis-ci/travis-api/pull/287 for Enterprise. 
/cc @rkh as the original author.
=> [Backport] Don't run Rack::Attack for Enterprise.

lib/travis/api/app.rb
On enterprise, the reverse proxy is not correctly set up, and therefore the client IP address not passed through properly. For that reason, all requests look like they originate from the same client, and if one gets blocked, everyone gets blocked.
=> Don't run Rack::Attack for Enterprise

Gemfile, Gemfile.lock
One of the important and tricky things when building an enterprise version is that every thing needs to be frozen at the same version. This is easy in the beginning when you first freeze. What gets trickier is later on when patching things. Then special care must be made to update to the correct version of the dependency. Since we use git backed gems in some places, one way to do this is to make sure each of the Gemfiles use the correct branch so they don't accidentally get put on `master` of some dependency while they themselves use a branch frozen from an earlier time. 
This is the solution I'm taking here. Essentially when we branch for a new enterprise version in the future, we'll need to place these branch statements in each of our own git backed gems. Another option is to use SHAs …
=> Use te-dev branch for travis-core in te-dev branch

lib/travis/api/v3/github.rb, lib/travis/api/v3/models/repository.rb, lib/travis/api/v3/models/ssl_key.rb, lib/travis/api/v3/services/repository/enable.rb
At the moment we don't upload SSL Key when activating a repository through V3, which breaks things for private repositories.
=> Upload SSL Key to GitHub when activating private repository

spec/spec_helper.rb, spec/unit/serialize/v2/http/jobs_spec.rb, spec/v3/models/cron_spec.rb
builds occasionally fail when the timestamps are a second off, this should fix that.
=> Fix Time Dependent Tests

lib/travis/config/url.rb, spec/lib/travis/config_spec.rb
Now that `travis-core` is vendored in `travis-api`, I needed to port the fixes done in https://github.com/travis-ci/travis-core/pull/559 in this project since it also doesn't yet use the 1.X version of `travis-config`.
=> Backport travis-core/travis-config AMQPS fix

.buildpacks, lib/travis/api/app.rb
We used last-commit-sha-buildpack in order to fetch the sha of the last
deployed commit during building the app and save it to use it later.
This was done using undocumented Heroku properties, for example it
assumed a certain path to git files. It turns out that there's another
way to do it now. We can enable [dyno-metadata](https://devcenter.heroku.com/articles/dyno-metadata) feature on heroku and
use `HEROKU_SLUG_COMMIT`
=> Use `HEROKU_SLUG_COMMIT` instead of last-commit-sha-buildpack

lib/travis/api/app/endpoint/home.rb, lib/travis/config/defaults.rb
`webhook.private_key` contains the public key corresponding
to the private key which `travis-tasks` uses to sign the webhook
payload.
See https://github.com/travis-ci/travis-tasks/pull/65
=> Add webhook to `/config` endpoint

lib/travis/api/v3/queries/user.rb, lib/travis/services/sync_user.rb, spec/lib/services/sync_user_spec.rb, spec/v3/services/user/sync_spec.rb
This makes API talk to the new queue and worker class in Sync 2.0
API v2 and v3 have been both tested on staging. I think this is ready to be merged.
v3 can be triggered like this:
```
curl -X PUT 'https://api-staging.travis-ci.org/user/3664/sync' \
-H 'Authorization: token **********************' \
-H 'Travis-API-Version: 3' \
-H 'Accept: application/json' 
```
=> Talk to Sync 2.0's queue

lib/travis/api/v3/models/build.rb, lib/travis/api/v3/services/build/restart.rb, lib/travis/api/v3/services/job/restart.rb, spec/v3/services/build/restart_spec.rb, spec/v3/services/job/restart_spec.rb
Trying to address https://github.com/travis-pro/team-teal/issues/1234
We believe that when restarting a job via the API, we should
clear the debug_options attribute so that the job can run as normal.
=> Clear debug options when restarting job

lib/travis/api/app/endpoint/authorization.rb, spec/unit/endpoint/authorization/user_manager_spec.rb
This triggers a sync not only when we first create a user, but also when the `github_oauth_token` changes.
Should help with this scenario: https://github.com/travis-pro/team-teal/issues/1305
/cc @rkh @renee-travisci @joecorcoran
=> Sync users on create and on github_oauth_token changed

lib/travis/api/app/endpoint/authorization.rb, spec/unit/endpoint/authorization/user_manager_spec.rb
This reverts commit 6d2380a1b3eaa170e414615f5ec0a297f329e23f.
Reverting this because people are not able to sign in on com. I'm not 100% sure this is what's causing the problem, but I think it's better to take it offline pending further testing.
=> Revert "sync users on create and on github_oauth_token changed"

lib/travis/api/app/endpoint/authorization.rb, spec/unit/endpoint/authorization/user_manager_spec.rb, spec/unit/endpoint/authorization_spec.rb
Re https://github.com/travis-pro/team-teal/issues/1332
This reverts commit d3154fea75c17f3c602545995fce5b6d05412aed, which reverted 6d2380a1b3eaa170e414615f5ec0a297f329e23f.
Opening this as a new branch so I can re-test things on com staging.
This now always syncs users on sign in.
=> Sync users on sign in

lib/travis/api/v3/models/json_slice.rb, lib/travis/api/v3/models/repository.rb, spec/v3/services/user_setting/update_spec.rb
This was an issue that @backspace found when working on travis-web.
Since we store lots of other things in the settings column besides
user settings, the attr has to be merged.
Also removes some ivar caching that didn't win us much in production
but made debugging hard.
=> Stop settings update from clobbering existing settings hash

lib/travis/api/v3/queries/user_setting.rb, lib/travis/api/v3/renderer/user_setting.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/user_setting/update.rb, spec/v3/services/user_setting/update_spec.rb
It came to my attention when writing the docs for these endpoints
that trying to accomodate the previous `setting.something` params
is not worth the hassle now that the resource is named `user_setting`.
This switches to `user_setting.something` but still allows
`setting.something` so that we can deploy this without breaking
travis-web.
=> Use uniform param names in settings endpoints

lib/travis/model/env_helpers.rb, spec/lib/model/job_spec.rb
We were making an effort to decrypt the name of the variable
but not the value (e.g. FOO=[secure]) but since this, under some
circumstance, can leak the value, this simply replaces the entire
variable (e.g. [secure]).
=> Replace entire secure env var with [secure]

lib/travis/api/app/endpoint/authorization.rb
travis-lite no longer appears to be in use or operational, remove it before the domain expires.
=> Remove safelist of travis-lite.com in API

Gemfile, Gemfile.lock
Updating to the latest (now correctly named) enterprise-2.0 version of travis-core which has the fix for sec-incident-20161007 in it.
=> Update travis-core to latest patch level for enterprise-2.0

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/permissions/repository.rb, lib/travis/api/v3/services/ssh_key/create.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/repositories/for_current_user_spec.rb, spec/v3/services/repositories/for_owner_spec.rb, spec/v3/services/repository/find_spec.rb, spec/v3/services/ssh_key/create_spec.rb, spec/v3/services/ssh_key/find_spec.rb
Requires that users have the correct permissions to regenerate
the key for a repo.
Additional to https://github.com/travis-ci/travis-api/pull/357
=> Fix up SSH key permissions

lib/travis/api/v3/queries/ssh_key.rb, spec/v3/services/ssh_key/create_spec.rb
Regenerated key was not persisted, since regenerate_keys! does not
call save!
=> Fix persistence bug

lib/travis/api/v3/models/cron.rb, lib/travis/testing/factories.rb, spec/v3/models/cron_spec.rb
Fixes sentry error : https://sentry.io/travis-ci/com-api-production/issues/189288118/events/4670632850/
=> Skip cron build if last build doesn't have finished_at

lib/travis/config/defaults.rb
The caches specs were failing because they weren't able to assign test cache_options config. The addition of this has in the default config fixes this.
=> add cache_options hash to config

Gemfile.lock, README.md, Rakefile
As migrations for the logs DB have been moved into `travis-migrations`, the readme needed updating to reflect this. 
There was also old commented-out code in the rakefile which was removed.
=> update readme, remove comments in rakefile

lib/travis/api/app/endpoint/authorization.rb
Github recently disallowed the use of iframes, rendering our iframe auth flow
obselete. In additional testing, it appears that the popup flow is also
failing (at least in Chrome), meaning this currently causes a several second delay (my
reading of the previous implementation suggests 10s) for a large portion
of our user base.
This removes the iframe and popup authentication. Additional details
can be found in https://github.com/travis-pro/team-teal/issues/1602.
=> Remove iframe and popup auth

lib/travis/api/v3/models/subscription.rb, spec/v3/models/subscription_spec.rb
This needs to be added for the `v3/accounts` endpoint to work.
See: https://github.com/travis-pro/team-teal/issues/1627
Tests are passing locally, on travis-ci, and these changes have been deployed to both org & com staging and tested there. The endpoint is now returning the correct payload on .com.
=> add active? method to subscription

lib/travis/api/v3/models/subscription.rb, spec/v3/models/subscription_spec.rb
This updates the recently added `active?` method on Subscription, removing the `cc_token` check, as some subscriptions are created manually and have no cc_token. It also conforms to the way Gatekeeper check for an active subscription, using `+ 1.day` and `- 1.day` on the timestamp.
Test are passing locally, on travis-ci, and have been deployed to com-staging (where the original problem with the `v3/accounts` endpoint appeared) and tested there.
=> update active? to remove cc_token check

lib/travis/api/v3/routes.rb, lib/travis/api/v3/routes/dsl.rb, lib/travis/api/v3/routes/resource.rb, lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
I realised that since the generated key pair resource and all related classes are named `SslKey` after the model/table, the name of the service was shown as `ssl_key` in the service index.
This adds the ability to add a "display identifier" to resources, so that we can rename resources from the API consumer's perspective without renaming our classes/resources in the codebase.
```ruby
resource :ssl_key, as: :key_pair_generated do
route '/key_pair/generated'
end
```
```
{
"@type": "home",
"@href": "/v3/",
...
"resources": {
"key_pair_generated": {
...
}
}
}
```
=> Add alias identifiers

lib/travis/model/user.rb, spec/lib/services/find_hooks_spec.rb
Hooks query times out from time to time for big number of repos.
Removing order seems to help a little bit. It isn't the best solution,
but for now it will help at least a little bit to lower the number of
timeouts.
=> Allow to remove order from hooks

lib/travis/api/v3/queries/env_vars.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/service.rb, lib/travis/api/v3/service_index.rb, lib/travis/api/v3/services/env_var/update.rb, lib/travis/api/v3/services/env_vars/create.rb, lib/travis/api/v3/services/user_settings/for_repository.rb, spec/v3/service_index_spec.rb, spec/v3/services/user_settings/for_repository_spec.rb
```
{
"@type"=>"template",
"request_method"=>"POST",
"uri_template"=>"/repo/{repository.slug}/requests",
"accepted_params"=> ["request.config", "request.message", "request.branch", "request.token"]
}
```
This is to:
* Allow better discoverability of our POST/PATCH services
* Add params automatically to the developer app (v3 docs)
This commit also changes the name of the `env_var` `Find` service to
`ForRepository`, which is in line with the other services.
=> Add allowed_params to POST & PATCH actions in service index

lib/travis/api/v3/models/log.rb, lib/travis/api/v3/queries/log.rb, lib/travis/api/v3/remote_query.rb, lib/travis/config/defaults.rb, lib/travis/model/user.rb, spec/v3/services/log/delete_spec.rb, spec/v3/services/log/find_spec.rb
While testing the log endpoint we discovered the remote_query class wasn't properly connecting to the s3 archive. 
The changes have been tested locally and on staging and the endpoint now operates as expected.
=> Fix Log endpoint so that it correctly connects to s3

lib/travis/api/v3/models/repository.rb, lib/travis/api/v3/models/ssl_key.rb, spec/v3/models/fingerprint_spec.rb, spec/v3/services/key_pair/create_spec.rb, spec/v3/services/key_pair/find_spec.rb, spec/v3/services/key_pair/update_spec.rb
Models which inherit from `Travis::Settings::Model` must use `#load` for instantiation, if they contain non-primitive attributes like `EncryptedValue`.
This PR also corrects the fingerprint calculation, which should always use the PEM as its source.
The key length has changed to bring the tests in line with V2, and also to speed up generation.
=> Load key pair properly

spec/spec_helper.rb
DatabaseCleaner is not cleaning up the logs database, which causes intermittent failures when logs and log_parts rows are left behind.
This avoids that issue by truncating the tables in the logs database after the test suite has run. I tried to get DatabaseCleaner running with two db connections, but it caused issues with nested transactions and I don't want to lose more time on it.
=> Truncate logs db after test run

lib/travis/api/v3/models/key_pair.rb, lib/travis/api/v3/models/repository.rb, spec/v3/services/env_vars/create_spec.rb, spec/v3/services/key_pair/create_spec.rb
We found an error where updating a key pair via PATCH resulted
in a rendering error. This was traced to the repo id on the key
pair being nil, because the create service was not setting it.
This also adds tests to cover that case, for key pairs and
env vars.
=> Ensure repo id is always set as additional attribute

Procfile, lib/travis/api/app/endpoint/authorization.rb, lib/travis/customerio.rb, lib/travis/sidekiq.rb
From commit message:
```
At the moment we need to wait for a customerio's response in order to
log a user in. I think that this might be causing problems for some
users. I'm not 100% certain that this is customerio's problem, but I
think that we should be running it in the background anyway. It's not
crucial for signing in, so we shouldn't be making a handshake call
longer than it needs to be.
I chose to run customerio in a separate thread. This is because I think
that putting it in sidekiq would be an overkill. There are only 2
downsides to using threads that I can imagine:
1. When the server is restarted the request might not reach customerio.
I don't think it's enough of a problem in reality. When an app is
deployed on Heroku it will wait till the old instance stops handling
requests …
```
=> Run customerio in background

Gemfile.lock, lib/travis/api/v3.rb, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/service.rb, lib/travis/api/v3/services/key_pair/create.rb, lib/travis/api/v3/services/key_pair/delete.rb, lib/travis/api/v3/services/key_pair/find.rb, lib/travis/api/v3/services/key_pair/update.rb, spec/support/shared_examples.rb, spec/v3/services/key_pair/create_spec.rb, spec/v3/services/key_pair/delete_spec.rb, spec/v3/services/key_pair/find_spec.rb, spec/v3/services/key_pair/update_spec.rb
This mirrors V2 api behaviour but in the single codebase.
The `PaidFeature` error is raised when a key pair action is
attempted, unless the repo is private or the api is running
on enterprise.
This is following advice re: enterprise and The Merge in
https://github.com/travis-ci/travis-api/pull/418.
=> Restrict access to key pair services to enterprise/private

lib/travis/api/v3/queries/cron.rb, lib/travis/api/v3/services/cron/create.rb, spec/v3/services/cron/create_spec.rb
This change conforms to previous conventions re namespacing of params on other endpoints, and reflects info in the developer documentation https://developer.travis-ci.org/resource/cron#create
=> add cron prefix to cron params

lib/travis/api/app/endpoint/authorization.rb
For some users we get a response that has a 200 status, but there's no
token. This commit adds logging of the response's body and headers in
order to get more information about the situation. This should be safe
as it will only output the body when token can't be found.
=> Log GitHub's response when token is missing

script/server-pgbouncer
In order to be able to perform a safe rollout of pgbouncer (https://github.com/travis-pro/dev/issues/9) on production, this patch allows enabling it selectively on a single dyno, by setting (for example) `PGBOUNCER_ENABLE_FOR_DYNO=web.5`.
=> pgbouncer: support enabling for a single dyno via env

lib/travis/config/defaults.rb
This PR removes repo filter to exclude `rails/rails` forks
- since this was in place when rails repo had our largest build matrix and the system couldn't support it
- this is no longer the case and we plan to introduce a more robust and nuanced fair usage policy, later on
Fixes https://github.com/travis-ci/travis-ci/issues/6907
=> Remove repository filters that excluded forks of rails/rails repo

script/server-pgbouncer
replaces `PGBOUNCER_ENABLED_FOR_DYNO` env var with `PGBOUNCER_ENABLED_FOR_DYNOS`,
a space-separated list.
this allows us to more selectively roll out to a subset of dynos, as opposed to only a single one. allowing us to add one dyno per day (or so).
the idea is that this will make the rollout slower, more incremental, and safer.
=> pgbouncer: support selectively enabling pgbouncer for more than one dyno

lib/travis/api/v3/renderer/cache.rb, lib/travis/api/v3/renderer/caches.rb
This is required for the Developer docs.
This branch has been deployed to org staging and the endpoint still returns the payload as before.
=> Add :branch and :name attributes to caches

lib/travis/api/serialize/v2/http/requests.rb, lib/travis/model/request.rb, lib/travis/services/find_requests.rb, spec/lib/services/find_requests_spec.rb, spec/spec_helper.rb, spec/unit/serialize/v2/http/requests_spec.rb
In order to slightly optimise requests page I would like to not preload
all the build data, but do a LEFT JOIN with builds to just get the id.
=> Optimise requests to not preload builds

lib/travis/api/v3/models/log.rb, lib/travis/api/v3/models/log_part.rb
it looks like the status quo may be creating 3 separate pools, leading to 3x50 pg connections instead of the allocated 50.
refs https://github.com/travis-pro/team-teal/issues/1775.
=> share postgres connection pool between all logs models

lib/travis/api/v3/logs_model.rb, lib/travis/api/v3/models/log.rb, lib/travis/api/v3/models/log_part.rb
@drogus raised a concern about the v3 Log and LogPart models inheriting
from Travis::LogsModel instead of Travis::API::V3::Model, as the shared
v3 base class has some extra behaviour that is now missing.
since we cannot inherit from both the v3 model as well as the v2
LogsModel, this patch addresses the problem by copy-pasting the v3
model, and inheriting from the v2 LogsModel.
any changes to Travis::API::V3::Model will need to be applied to
Travis::API::V3::LogsModel as well. at least until api v2 and v3
are split into separate repos.
this is a temporary(tm)* fix.
*probably forever <3
refs https://github.com/travis-ci/travis-api/pull/445, https://github.com/travis-pro/team-teal/issues/1775
=> introduce separate LogsModel for v3 so that all v3 models inherit the same behaviour

lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
All resources listed in the service index have the templates in their actions listed as an array (main reason being that URI templates don't support unions), except for the `home` entry.
This PR fixes it.
@mislav reported this issue a long time ago via Slack, but I only just came across it again while playing reviewing the API. Automated scripts are likely to run into this issue.
=> API v3: Fix 'home' entry in service index

lib/travis/api/app.rb, lib/travis/api/app/endpoint/builds.rb, lib/travis/api/app/endpoint/jobs.rb, lib/travis/api/app/helpers/respond_with.rb, lib/travis/api/app/responders/json.rb, lib/travis/api/serialize/v0/pusher/job.rb, lib/travis/api/serialize/v2/http/build.rb, lib/travis/api/serialize/v2/http/job.rb, lib/travis/api/serialize/v2/http/jobs.rb, lib/travis/api/serialize/v2/http/remote_log.rb, lib/travis/api/v3/models/log.rb, lib/travis/api/v3/queries/log.rb, lib/travis/remote_log.rb, spec/integration/v2/jobs_spec.rb, spec/lib/travis/remote_log_spec.rb, spec/unit/serialize/v2/http/job_spec.rb, spec/unit/serialize/v2/http/jobs_spec.rb, spec/v3/services/log/find_spec.rb
plus (back?) to conditionally including a job's `log_id` in order to make the interactions with the travis-logs API *much* less chatty during normal use via travis-web while retaining compatibility with https://github.com/travis-ci/travis.rb.
=> Ensure RemoteLog serializes more like direct database Log

lib/travis/api/app.rb, lib/travis/api/app/endpoint/builds.rb, lib/travis/api/app/endpoint/jobs.rb, lib/travis/api/app/responders/json.rb, lib/travis/api/serialize/v0/pusher/job.rb, lib/travis/api/serialize/v2/http/build.rb, lib/travis/api/serialize/v2/http/job.rb, lib/travis/api/serialize/v2/http/jobs.rb, lib/travis/api/serialize/v2/http/remote_log.rb, lib/travis/api/v3/constant_resolver.rb, lib/travis/api/v3/models/job.rb, lib/travis/api/v3/models/log.rb, lib/travis/api/v3/models/remote_log.rb, lib/travis/api/v3/queries/log.rb, lib/travis/api/v3/renderer.rb, lib/travis/model/remote_log.rb, lib/travis/remote_log.rb, spec/integration/v2/builds_spec.rb, spec/integration/v2/jobs_spec.rb, spec/lib/travis/remote_log_spec.rb, spec/unit/serialize/v2/http/job_spec.rb, spec/unit/serialize/v2/http/jobs_spec.rb, spec/v3/services/log/find_spec.rb
Reverts travis-ci/travis-api#464
=> Revert of Revert of Ensuring RemoteLog serializes more like direct database Log

lib/travis/api/app/schedulers/schedule_cron_jobs.rb
Much like https://github.com/travis-ci/travis-logs/pull/95 we often can only see 2000 lines of a customers logs, so anything that makes them chatty with low information can easily fill them up and make us miss problems. Many times we have logs that look like this: 
```
[2017-03-31T17:18:59+0000][travis-pro-api:cron] I TID=70024447185160 Found 0 cron jobs to enqueue
[2017-03-31T17:19:59+0000][travis-pro-api:cron] I TID=70024447185160 Found 0 cron jobs to enqueue
[2017-03-31T17:20:59+0000][travis-pro-api:cron] I TID=70024447185160 Found 0 cron jobs to enqueue
[2017-03-31T17:21:59+0000][travis-pro-api:cron] I TID=70024447185160 Found 0 cron jobs to enqueue
[2017-03-31T17:22:59+0000][travis-pro-api:cron] I TID=70024447185160 Found 0 cron jobs to enqueue …
```
=> [Enterprise] Make cron logs less chatty when theres nothing to enqueue

lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
Stage objects are now returned within build and job payloads by API v3, but as there's no endpoint for stages at the moment, the service index did not pick it up automatically. This fixes it, and the home document will now include:
``` json
{
"stage": {
"@type": "resource",
"actions": {
},
"attributes": ["id","number","name","jobs"],
"representations": {
"minimal": [
"id",
"number",
"name"
],
"standard": [
"id",
"number",
"name",
"jobs"
],
"active": [
"id",
"number",
"name",
"jobs"
]
}
}
}
```
It also removes the `account` entry, fixing travis-pro/team-teal#1838.
=> v3: add stage resource to service index, remove account

lib/travis/api/v3/models/build.rb, lib/travis/api/v3/models/job.rb, lib/travis/model/build.rb, lib/travis/model/job.rb, lib/travis/model/request.rb, lib/travis/testing/factories.rb, spec/unit/model/build_spec.rb, spec/unit/model/job_spec.rb, spec/v3/models/build_spec.rb, spec/v3/models/job_spec.rb
Gatekeeper does not set `build.state` and `job.state` to `created` at the moment in order to help prevent a race condition that might end up queueing jobs twice when it shouldn't. We might keep this in place in Gatekeeper for a while, just to be sure, but we should not expose it to the user.
=> default job and build state to :created

lib/travis/api/app/endpoint/authorization.rb, lib/travis/model/user.rb, spec/unit/endpoint/authorization/user_manager_spec.rb
From the commit message
```
We still use user tokens that are stored in `tokens` table to
authenticate status images and cc.xml requests. Because of that
travis-web does a check for a token when it fetches the user. Recently
we started creating new user records outside of auth flow - we're basing
it on GitHub payloads. It means that some of the users may not have a
token available. We don't need tokens for users that never signed in, so
the best thing to do is to create a token when a user tries to sigin in.
```
=> Create `User#tokens` record on sign up

lib/travis/api/v3/model_renderer.rb, lib/travis/api/v3/renderer/build.rb, lib/travis/api/v3/renderer/job.rb, lib/travis/api/v3/renderer/repository.rb, lib/travis/api/v3/renderer/stage.rb, lib/travis/api/v3/service_index.rb
This addresses this issue: https://github.com/travis-pro/team-teal/issues/1915
The changes are aimed at hiding certain representations from the Service Index, as they are used for experimental features, or for endpoints that require an 'active' representation defined, despite it being an exact copy of a 'standard' representation (see the issue linked above for an explanation of why this is necessary).
Hiding these from the Service Index will mean they won't appear in the API V3 Developer docs, which will avoid further confusion in that regard.
This has been deployed on org-staging and all working as intended.
`developer` has been redeployed to staging to injest the changes. 
All working there as expected too: https://developer-staging.travis-ci.org/resource/build#Build
=> Add hidden_representations to exclude :active from service index

lib/travis/api/enqueue/services/restart_model.rb
this missing check is causing the following error message for unauthenticated
users:
NoMethodError: undefined method `permission?' for nil:NilClass
Fixes https://sentry.io/travis-ci/org-api-production/issues/244070234/
=> restart_model: ensure user is logged in before permission check

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/queries/request.rb, lib/travis/api/v3/renderer/request.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/request/find.rb, spec/v3/services/request/find_spec.rb
Backporting #489 for Enterprise 2.1. 
Can I get a review on how this looks I had the following conflicts and want to make sure I merged them right. Particularly request.rb: 
Conflicts:
lib/travis/api/v3/renderer/request.rb
lib/travis/api/v3/routes.rb
=> [Enterprise Backport] Add `/request/:id` endpoint #489

lib/travis/api/v3/models/cron.rb, spec/v3/models/cron_spec.rb
Instead of checking the `finished_at` time to find if there has been a build in the last 24h, check for the `started_at` time. This ensures that daily builds aren't skipped for cases where builds take longer than a minute.
Fixes: https://github.com/travis-pro/team-teal/issues/1734
=> Check for started_at for a recent build

lib/travis/model/repository/settings.rb
This ensures that using V2 settings endpoint will not overwrite cancellation settings. The proper fix will be to make V2 settings merge data instead of overwrite, I hope to also do it soon.
=> Add auto cancel settings to V2 model

lib/travis/api/v3/queries/builds.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/builds/for_current_user.rb, spec/v3/services/builds/for_current_user.rb
This addresses this ticket: https://github.com/travis-pro/team-teal/issues/2005 which would like the ability to list a user's builds on a tab of their dashboard.
I've chosen to implement the endpoint by using a `for_current_user` action on the `/builds` endpoint. 
This is similar to `/repos` and `/broadcasts`, which also use a `for_current_user` action to list repos or broadcasts for the current logged-in user. 
A test has been added and is passing. The branch has also been deployed to org-staging and, using the explorer on the updated developer docs, is returning builds as expected.
=> Add support for `/builds` for_current_user on V3 API 

lib/travis/api/v3/models/build.rb, lib/travis/api/v3/queries/repositories.rb, lib/travis/api/v3/renderer/build.rb, spec/v3/models/build_spec.rb
1. The following request was noticed to be very slow:
```
curl -iL -H "Authentication: token abc" \
https://api.travis-ci.org/v3/owner/travis-ci?include=owner.repositories,repository.current_build
```
2. This was tracked down to the lack of [preloading in
v3/queries/repositories.rb](https://github.com/travis-ci/travis-api/blob/jc-slow-repos/lib/travis/api/v3/queries/repositories.rb#L48) when including `repository.current_build`
3. More work was then required to get the rendering to work,
because the polymorphic `belongs_to` between `build` and `sender` is
not smart enough to work out that we need the V3 namespaced
model and renderer classes. [Details here](https://github.com/travis-ci/travis-api/commit/cef85e52618258cad6553fa9131cb59db920a9ab).
I've run this locally, connected to the org …
=> Include nested resources to avoid n+1 queries

lib/travis/testing/stubs.rb, spec/lib/schedulers/schedule_cron_jobs_spec.rb, spec/unit/serialize/v2/http/job_spec.rb, spec/v3/models/cron_spec.rb, spec/v3/services/beta_feature/update_spec.rb
My hope is that this will fix these kinds of issues:
```
-"committed_at" => "2017-07-03T09:37:51Z",
+"committed_at" => "2017-07-03T09:37:50Z",
```
=> make sure to always re-freeze timecop

Gemfile.lock, lib/travis/api/app/endpoint/authorization.rb, spec/integration/error_handling_spec.rb
Fixes this issue that the previous patch had: https://sentry.io/travis-ci/org-api-production/issues/304707588/
refs https://github.com/travis-ci/travis-api/pull/511
=> Re-introduce sentry and faraday update

lib/travis/api/v3/service.rb, lib/travis/api/v3/services/build/restart.rb, spec/v3/services/build/restart_spec.rb
@aakritigupta I added a rejected method, similar the accepted method that returns a json error message about abuse. Please let me know if this is what you were looking for.
=> Suggestion for rejecting restarts for abusive accounts

lib/travis/api/app.rb, lib/travis/api/app/services/schedule_request.rb, lib/travis/api/sidekiq.rb, lib/travis/api/v3/models/cron.rb, lib/travis/api/v3/queries/request.rb, lib/travis/api/v3/sidekiq.rb, lib/travis/config/defaults.rb, spec/v3/services/requests/create_spec.rb
refs https://github.com/travis-pro/team-teal/issues/2064
travis-api enqueues messages to gatekeeper. this patch adds support for enqueueing to gatekeeper's dedicated sidekiq redis instance.
this is modeled after what we have in gatekeeper:
* https://github.com/travis-ci/travis-gatekeeper/blob/master/lib/travis/sidekiq.rb
=> enqueue gatekeeper messages to separate redis

lib/travis/remote_log.rb
In Enterprise we sometimes deal with self signed certs and certs signed by CAs that aren't standard. As a result we do some configuration of SSL and things like add the cert to the bundles located in `/usr/lib/ssl/certs/ca-certificates.crt`. 
When setting up the new logs for 2.2 I ran into an issue where `travis-api` couldn't read from the  logs end point due to not being able to verify the SSL cert. In other places we usually blend in the ssl options (eg https://github.com/travis-ci/travis-api/blob/2c3540b9eb4328d891fc3c2234f8a3ed0f9acc5d/lib/travis/task.rb#L78-L87) but weren't in this case. 
This PR attempts to fix that by merging in these options. 
-----------------
Later edit: Also fixed in this is some API path issues where we used a leading `/`. When we do that it causes the way we …
=> Include the ssl options from config when grabbing remote logs

lib/travis/api/v3/models/cron.rb, spec/v3/models/cron_spec.rb
Fixes https://github.com/travis-pro/team-teal/issues/2037 : Cron build is started even if the repository is disabled
=> Remove cron if repo has been disabled

Gemfile
to avoid logs like:
```
-----> Detecting rake tasks
Could not detect rake tasks
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
rake aborted!
cannot load such file -- knapsack
```
during deployment.
=> Install knapsack for all environments

Gemfile, Gemfile.lock, lib/travis/api/serialize/v2/http/user.rb, spec/integration/v2/users_spec.rb, spec/unit/endpoint/users_spec.rb, spec/unit/serialize/v2/http/user_spec.rb
We plan to move to a per-user channel instead of per-repo channels. This
commit skips sending channels for repositories belonging to owners with
per-user channels enabled.
=> Omit repo pusher channels for a user when per-user channel is enabled

README.md, lib/travis/api/v3/queries/builds.rb, lib/travis/api/v3/queries/jobs.rb, lib/travis/api/v3/queries/stages.rb, lib/travis/api/v3/renderer/stages.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/stages/find.rb, spec/v3/services/stages/find_spec.rb
This addresses the issue of timeouts when loading the Build History page in web when a repository has many builds with hundreds of jobs each.
https://github.com/travis-pro/team-teal/issues/2145
It was necessary to implement a `stages` endpoint: `/build/{build.id}/stages`
I also have commented out the filter on `builds` for `build.jobs` as this was the part of the request causing the timeout. (`build.jobs` was necessary in order to find the `build.stages`)
I've added local tests and deployed to staging. The new endpoint works and nothing seems to be effected re `build.jobs`
=> add stages endpoint

lib/travis/api/serialize/v2/http/build.rb, lib/travis/api/serialize/v2/http/builds.rb, lib/travis/api/serialize/v2/http/job.rb, lib/travis/api/serialize/v2/http/jobs.rb, lib/travis/api/v3/models/build.rb, lib/travis/api/v3/models/commit.rb, lib/travis/api/v3/models/tag.rb, lib/travis/api/v3/queries/builds.rb, lib/travis/api/v3/renderer/build.rb, lib/travis/api/v3/renderer/tag.rb, lib/travis/api/v3/result.rb, lib/travis/model/commit.rb, lib/travis/testing/stubs.rb, spec/unit/serialize/v2/http/build_spec.rb, spec/unit/serialize/v2/http/builds_spec.rb, spec/unit/serialize/v2/http/job_spec.rb, spec/unit/serialize/v2/http/jobs_spec.rb, spec/v3/services/build/find_spec.rb, spec/v3/services/builds/find_spec.rb
This adds a `tag` to the `build` payloads in v3 like:
```
{
"@type"           => "tag",
"@representation" => "minimal",
"repository_id"   => 1,
"name"            => "v1.0.0",
"last_build_id"   => 1
}
```
I am not entirely sure this is what we want, or all we want. I have not added the `tag` to `job` because those also don't have a `branch`.
=> Add tag to v3 build payloads

lib/travis/api/serialize/v2/http/user.rb, spec/integration/v2/users_spec.rb, spec/unit/endpoint/users_spec.rb, spec/unit/serialize/v2/http/user_spec.rb
Since the recent switch to per-user channels we always use public user
channel on .org and private user channel on .com. This doesn't make a
lot of sense, especially that when we merge the platforms, we will stay
with only private user channel. To unify the behaviour and simplify the
code in other places, this commit changes API to subscribe user to both
public and private user channels, which will allow to seamlessly switch
the rest of the apps to use private user channel (and then we can drop
public user channel).
=> Subscribe to private user channel

lib/travis/api/serialize/v2/http/user.rb, spec/integration/v2/users_spec.rb, spec/unit/endpoint/users_spec.rb, spec/unit/serialize/v2/http/user_spec.rb
travis-live already sends messages only to a private channel, so there's
no need to keep the public channel in the response
=> Only send private user channel from pusher channels

lib/travis/api/app/middleware/error_handler.rb, lib/travis/testing/stubs.rb, spec/integration/error_handling_spec.rb
This allows users to make reports with that id, that we can correlate in sentry to get the actual exception.
=> include request_id in 5xx error responses

lib/travis/api/v3/queries/branches.rb, spec/v3/services/branches/find_spec.rb
Sorting without `NULLS LAST` results with not started builds on the beginning, which isn't really something that we want.
=> Sort branches by `last_build.started_at NULLS LAST`

lib/travis/api/v3/queries/branches.rb, spec/v3/services/branches/find_spec.rb
After I committed 755b831 I realised that this is still not right. When
you restart a job and cancel it right away, started_at will be set to
null, so even though the build might be new, the branch will be put at
the end of the results. Even if we defaulted to the previous behaviour
of NULLs going to the beginning, it would still not be entirely right,
because an old branch with a cancelled build could come up on top.
Sorting by id seems like a best way to achieve what we want, ie. sort by
the most recent build.
=> Sort branches.last_build by last_build.id

lib/travis/api/v3/queries/jobs.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/active/for_current_user.rb, lib/travis/api/v3/services/jobs/for_current_user.rb, spec/v3/services/jobs/find_for_current_user_spec.rb
This PR adds a `/jobs` endpoint that returns jobs from repositories to which a user has access. It can be filtered using `active` param, which will return only jobs that are currently "active", ie. either queued or running.
=> `/jobs` endpoint

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/services/beta_feature/delete.rb, lib/travis/api/v3/services/beta_feature/update.rb, lib/travis/api/v3/services/beta_features/find.rb, spec/v3/services/beta_feature/delete_spec.rb, spec/v3/services/beta_feature/update_spec.rb, spec/v3/services/beta_features/find_spec.rb
Checking only for user visibility is not enough as it will be true for
all of the logged in users, that's why we need to explicitly check for
beta_features visibility.
=> Properly check beta_features visibility

lib/travis.rb, lib/travis/api/app/middleware/error_handler.rb, spec/integration/error_handling_spec.rb, spec/spec_helper.rb
Every time I work in API the first thing I do is to go to the [error handler middleware](https://github.com/travis-ci/travis-api/blob/8fac307ad258becd0a1b2c44c1b257232d7d65b0/lib/travis/api/app/middleware/error_handler.rb#L10) and remove the rescue part, so I get actual exceptions when running tests rather than the `Sorry, we experienced an error` response. So, I decided that I need to finally fix it for everyone.
=> Raise exceptions when testing

lib/travis/model/request.rb
Taking a look at the code, I've found that there are two defined
relations with the repository model. I've read the request model in
travis-core and there it has only one of it so it seems like a typo
or mistake
=> Request relation with repository is duped

lib/travis/api/v3/queries/jobs.rb
We should always include build when fetching jobs and commit if it's in
an `include` query param
=> Avoid N+1 queries problem in /builds/:id/jobs

Gemfile, Gemfile.lock, lib/travis/testing/matchers.rb, spec/v3/services/branches/find_spec.rb, spec/v3/services/build/find_spec.rb, spec/v3/services/builds/find_spec.rb, spec/v3/services/builds/for_current_user.rb, spec/v3/services/cron/create_spec.rb, spec/v3/services/cron/delete_spec.rb, spec/v3/services/cron/find_spec.rb, spec/v3/services/cron/for_branch_spec.rb, spec/v3/services/crons/for_repository_spec.rb, spec/v3/services/job/find_spec.rb, spec/v3/services/jobs/find_spec.rb, spec/v3/services/lint/lint_spec.rb, spec/v3/services/repository/find_spec.rb, spec/v3/services/stages/find_spec.rb
From the commit message:
```
In API V3 specs we often compare big JSON objects and when 2 objects
don't match, we get a message that's not very helpful: expected (...big
pile of JSON here...) to be equal to (...another big pile of JSON
here...).
This commit introduces eql_json matcher that will return a better
message. For example given the following expectation:
actual = {
'job' => {
'id' => 1,
'number': '10.1',
'repository_id': 1
}
}
expect(actual).to eql_json({
'job' => {
'id' => 1,
'number': '11.1',
'state': 'passed'
}
})
The message will be:
Failure/Error: expect(actual).to eql_json({
expected to match JSON:
missing job.state == passed
entries @job.number do not match, expected: 11.1, actual: 10.1
extra entry job.repository_id == 1
This makes it much easier to fix any potential …
```
=> Add `eql_json` rspec matcher

lib/travis/api/v3/github.rb
This allows to create read/write deploy keys for a specified owner.
=> Allow to create read/write keys

lib/travis/api/v3/model_renderer.rb, lib/travis/api/v3/renderer/build.rb, lib/travis/api/v3/renderer/job.rb, spec/lib/services/find_build_spec.rb, spec/support/formats.rb, spec/v3/services/build/find_spec.rb, spec/v3/services/builds/find_spec.rb, spec/v3/services/job/find_spec.rb, spec/v3/services/jobs/find_spec.rb
From the commit message:
```
API responses and live updates (delivered by Pusher) may sometimes come
to the client out of order. That's why we want to have a way to version
records to be able to compare them and apply only the newest updates.
updated_at column seems like a good way to check record's version, so
this commit adds it to job's and build's payload.
We might consider adding it to other records as well, but for now these
are two most important tables.
```
=> Return `updated_at` column for jobs and builds

lib/travis/api/app/base.rb
One of the things we've noticed in Enterprise is that logging is off so it can be difficult to see when things are hitting the API without looking at `nginx.log`. Additionally we've noticed that errors are not dumped properly, causing Sentry to swallow them. This is something that may be in how Sentry is configured (or logging) in `travis-api` vs the rest of the apps. 
This PR attempts to solve this issue by enabling logging and dumping errors in Enterprise only. 
This way we can see more of what's happening and hopefully get to roots of problems sooner.
=> Enable logging and dumping errors in Enterprise for easier debugging

lib/travis/api/v3/access_control.rb, lib/travis/api/v3/access_control/log_token.rb, lib/travis/api/v3/log_token.rb, lib/travis/api/v3/models/log.rb, lib/travis/api/v3/queries/log.rb, lib/travis/api/v3/renderer/log.rb, lib/travis/api/v3/router.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/log/find.rb, spec/v3/services/log/find_spec.rb
This PR adds a feature that we have in V2, but is missing from V3 - ability to fetch private logs with a supplied token. Whenever we return a log response it will now contain `@raw_url`, which will lead to a text version of the log and which will contain a token for private version. I needed to use `log.token` instead of just `token` in the query params, because otherwise V2 picks it up. That doesn't really matter much, though, because since we return the full URL we can rename the query param later without breaking stuff.
=> Add private log token

lib/travis/model/job.rb, lib/travis/secure_config.rb, spec/lib/model/job_spec.rb
if somebody sets an env var that has a float value in yml, we currently pass it all the way through to the decryptor, which errors out, because it expects a string or an array.
this has produced a very high error volume.
=> handle potentially encrypted float values

lib/travis/api/app/schedulers/schedule_cron_jobs.rb
This is part of the making logs less chatty in Enterprise effort where even when there's no activity on the instance the logs still generate a lot of chatter which can make diagnosing problems difficult (as we only grab recent logs). 
The approach I went with here was to only show the log message when there was something to enqueue in Enterprise. In hosted it'll still show the log entry when there's nothing to enqueue (so no change). I could see making them behave the same, but since I don't know how these messages are used in hosted I did the safest approach.
=> Make cron enqueue messages only show when there's something to enqueue in Enterprise

lib/travis/api/v3/service_index.rb
we are seeing strange things on the service index, like:
"attributes": "#<Set:0x00007f456c9cfed8>",
"representations": {
"standard": "#<Set:0x00007f456c9cfed8>"
}
this is likely a regression from the activerecord upgrade.
refs #599
=> recursively convert sets to arrays before rendering

config/nginx.conf.erb
This allows us to change the log level to `info` (http://nginx.org/en/docs/ngx_core_module.html#error_log) so that we can see nginx level errors in more detail.
The level can be set via:
```
heroku config:set NGINX_ERROR_LOG_LEVEL=info -a travis-api-staging
```
The error logs can be viewed by running:
```
heroku ps:exec -a travis-api-staging 'tail -F logs/nginx/error.log'
```
=> make nginx error log level configurable

Gemfile, Gemfile.lock, lib/travis/api/app.rb, lib/travis/api/v3/router.rb, lib/travis/marginalia.rb
The idea of this is to add comments to all queries with some context about where the query came from. This way, when it pops up in the slow query log, we can instantly correlate it with the code.
This is using the [marginalia](https://github.com/basecamp/marginalia) gem, which is a light wrapper on top of activerecord (with some additional railsy dependencies unfortunately).
This prototype already looks quite promising, I'm getting this kind of output:
```
D TID=70130997244500   Travis::API::V3::Models::Repository Load (1.6ms)  SELECT  "repositories".* FROM "repositories" INNER JOIN "permissions" ON "permissions"."repository_id" = "repositories"."id" INNER JOIN "users" ON "users"."id" = "permissions"."user_id" WHERE "repositories"."invalidated_at" IS NULL AND "users"."id" = $1 AND …
```
=> postgres query comments via marginalia

lib/travis/api/app.rb, lib/travis/api/app/middleware.rb, lib/travis/api/app/middleware/log_tracing.rb, lib/travis/api/app/middleware/rewrite.rb
This is a simplified log-based solution that will eventually be replaced by zipkin (travis-ci/travis-api#598).
It allows us to trace SQL queries either per request (by setting the `Trace: true` request header) or per user (by setting the `LOG_TRACING_ENABLED_FOR_LOGIN` env var).
Log tracing must be enabled globally via the `LOG_TRACING_ENABLED` environment variable (must be set to `true`).
=> log-tracing: introduce log-based tracing for requests

config/nginx.conf.erb, lib/travis/api/app/cors.rb, spec/unit/cors_spec.rb
=> log-tracing: include X-Request-ID in Access-Control-Expose-Headers

lib/travis/api/app.rb, lib/travis/api/v3/model_renderer.rb, script/request
This helps track down n+1 queries, by showing a logical backtrace for where in the rendering process the query happened.
An example output:
```
D TID=70269398153540   Travis::API::V3::Models::Organization Load (0.6ms)  SELECT  "organizations".* FROM "organizations" WHERE "organizations"."id" = $1 LIMIT 1  [["id", 1271]]
D TID=70269398153540    (0.5ms)  SELECT COUNT(*) FROM "permissions" WHERE "permissions"."user_id" = $1 AND "permissions"."user_id" = $2 AND "permissions"."pull" = $3 AND "permissions"."repository_id" = 62295  [["user_id", 4280], ["user_id", 4280], ["pull", "t"]]
D TID=70269398153540    (0.4ms)  SELECT COUNT(*) FROM "permissions" WHERE "permissions"."user_id" = $1 AND "permissions"."user_id" = $2 AND "permissions"."admin" = $3 AND "permissions"."repository_id" = 62295 …
```
=> model-renderer-tracing: correlate sql queries with the fields in the model they originate from

spec/v3/services/job/find_spec.rb
When I ran tests locally I noticed one for v3/services/job/find_spec.rb was using the wrong job object. For some reason it wasn't failing on Travis, but this fix now passes locally and on Travis...
=> change to correct job

lib/travis/api/v3/models/message.rb, lib/travis/api/v3/models/request.rb, lib/travis/api/v3/queries/messages.rb, lib/travis/api/v3/renderer/build.rb, lib/travis/api/v3/renderer/message.rb, lib/travis/api/v3/renderer/messages.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/messages/for_request.rb, spec/v3/services/messages/for_request_spec.rb
This PR addresses https://github.com/travis-pro/team-teal/issues/2285, which is part of the `travis-yml` project.
It adds a v3 api endpoint to find any `messages` that may have been created for a `request` by `travis-yml`.
All tests are passing, and the branch has been deployed and tested on staging with test data. See here for sample payload: https://api-staging.travis-ci.org/v3/repo/travis-repos%2Fchirp-org-staging/request/247096/messages
=> Add .../repo/id/request/id/messages endpoint for display of travis-yml messages

lib/travis/api/v3/service_index.rb
This is needed for the developer documentation.
It's bee deployed to staging with no errors.
Tests are passing on Travis.
=> add dummy message resource

lib/travis/api/v3/renderer/build.rb, spec/v3/services/build/find_spec.rb
/v3/build/123?include=build.request
The minimal representation of a request is included in the build
response, but only when using the include param as above.
=> Allow build response to contain request

Gemfile.lock, lib/travis/model/encrypted_column.rb, spec/integration/v2/settings/env_vars_spec.rb, spec/v3/services/env_var/find_spec.rb
When we decrypt a string using OpenSSL it gives it ASCII-8BIT encoding
by default. We need to encode it in UTF-8 in order to not raise errors
with UTF-8 characters.
=> Fix decrypting env vars with non-ascii characters

lib/travis/model/repository.rb, lib/travis/services/find_user_accounts.rb, spec/lib/model/repository_spec.rb, spec/lib/services/find_user_accounts_spec.rb, spec/unit/endpoint/accounts_spec.rb
From the commit:
```
find_user_accounts service that we use to fetch accounts and
repositories names was querying accounts by getting a list of user
repositories and then using an owner_name attribute to fetch
organizations. This method will work only if we don't have any
duplicates in the database. Duplicates can happen in multiple scenarios,
for example when an organization is deleted from GitHub and a new one is
created. We don't delete old organizations at the moment, so fetching by
name will get both records.
This commit changes the code to fetch organizations by ids rather than
by names.
In theory we could use memberships to fetch organizations (so basically
do `SELECT organization_id FROM memberships WHERE user_id = ?`), but I'm
not sure if this change would have any side effects, …
```
=> Fix fetching accounts when account names are duplicated in the DB

lib/travis/api/v3/queries/organization.rb, lib/travis/api/v3/queries/user.rb, spec/v3/queries/organization_spec.rb, spec/v3/queries/user_spec.rb
From the commit:
```
We sometimes might have more than one User or Organization record with
the same login in the DB. At the moment we don't invalidate them, which
means that there's a possibility that a user will get repositories from
an older organization. This doesn't really pose any security threat,
because we filter the repositories with a data from permissions table,
but it can result in confusing bugs for the users.
This commit changes queries used to fetch user and organization records
by logins to fetch records with the newest ids. This might not be 100%
accurate, so in the long run we should start invalidating old records,
but it should work in majority of cases (if not all cases).
```
=> Fetch the newest organization and user

lib/travis/model/repository.rb, lib/travis/services/find_user_accounts.rb, spec/lib/model/repository_spec.rb, spec/lib/services/find_user_accounts_spec.rb, spec/unit/endpoint/accounts_spec.rb
When fixing a bug in fetching accounts I actually introduced another
problem that I caught only when testing on staging. The previous code
was searching for Organizations also using a user id, which could result
in fetching an Organization with the same id as a user, even thought the
organization might not be related to the user at all. This commit fixes
the problem.
=> Fix fetching accounts for a user

lib/travis/api/v3/queries/repositories.rb, spec/v3/services/repositories/filter_spec.rb
When we were searching by slug we were querying the database for an
owner name and a repo name with all characters converted to lower case.
But the filter string was not converted, which means that it needed to
be in all lower case letters already. This commit fixes the problem by
converting a filter string to lower case as well.
=> Fix filtering by slug with uppercase letters

lib/travis/services/find_user_accounts.rb, spec/lib/services/find_user_accounts_spec.rb, spec/unit/endpoint/accounts_spec.rb
The method of counting repositories when fetching user accounts didn't
take permissions into account. Because of that the number could be wrong
if user doesn't have access to some of the repositories in an
organization.
This commit fixes it by combining fetching organizations and repos
counts into one query.
=> Don't include repos that user doesn't have access to in counts

lib/travis/api/app.rb, lib/travis/api/app/middleware/error_handler.rb, spec/integration/error_handling_spec.rb
this will make the error codes from api directly copy-pasteable into sentry, allowing for faster correlation.
=> change sentry tag from x_request_id to request_id

lib/travis/remote_log.rb, lib/travis/task.rb
Seeing an issue where API can't talk to the logs API when using a self signed cert. The SSL config fixes this but due to calling `compact` on `Travis.config.ssl` instead of `Travis.config.ssl.to_h` (as travis config objects are no longer a subclass of `Hash`) it will always be nil as it's looking for a config key called compact and there is none.
=> Fix always nil SSL config block in Enterprise

script/request
* user is now configurable
* errors produce a plaintext stack trace
* print a summary sql query count at the end
extracted from travis-ci/travis-api#614
=> script/request: improve ux

lib/travis/services/find_builds.rb, lib/travis/services/find_jobs.rb, lib/travis/services/find_repos.rb, spec/auth/v1/builds_spec.rb, spec/auth/v1/jobs_spec.rb, spec/auth/v1/repos_spec.rb, spec/auth/v2.1/builds_spec.rb, spec/auth/v2.1/jobs_spec.rb, spec/auth/v2.1/repos_spec.rb, spec/auth/v2/builds_spec.rb, spec/auth/v2/jobs_spec.rb, spec/auth/v2/repos_spec.rb, spec/lib/services/find_builds_spec.rb, spec/lib/services/find_jobs_spec.rb, spec/lib/services/find_repos_spec.rb
After switching from travis-pro-api to travis-api to serve traffic on
Travis CI Pro it turned out that there're differences in how certain
endpoints return the data. In travis-pro-api we were scoping all of the
endpoints to return only the stuff that belongs to a user. In travis-api
we return records to which a user has access to *and* public data. This
makes sense in most of the places, but not for `/repos`, `/builds` or
`/jobs`. The assumption there is that you get only your data when you do
an authenticated request, not your data and some random public records.
This issue will require setting `public_repos_in_v2_root_endpoints` config option to true on .org. I went with the flag, because we want to keep the behaviour unchanged on .org, but change it for everything else (ie. .com and …
=> Fix some V2 endpoints to not include public stuff on .com

lib/travis/api/app/endpoint/authorization.rb
For some reason Folding together the two SSL options pieces now breaks turning off SSL verification for self signed certs. Seems that you can't set a ca bundle AND turn off verify with Faraday? Maybe some change has been shipped there. 
So let's just control this from the GitHub config block like we used to.
=> Fix SSL errors during Authorization against GitHub Enterprise with self signed cert

lib/travis/api/app/endpoint/authorization.rb
Reverts travis-ci/travis-api#657
Ended up going a different direction with this where merging in the `ca_file` would make sense again. Now the `verify: false` setting is configurable in the interface so reverting this makes sense.
=> Revert "Fix SSL errors during Authorization against GitHub Enterprise with self signed cert"

lib/travis/api/v3/paginator.rb, lib/travis/api/v3/paginator/count_cache.rb
For a lot of endpoints, the pagination count query is the biggest performance bottleneck. The fundamental issue is that counts are expensive. If there are many records, a count essentially means we need to do a full scan of all those records.
As a long-term solution we should probably move away from count-based pagination in the case of large tables (builds and jobs). There are faster pagination approaches described in [Pagination Done the Right Way](https://use-the-index-luke.com/blog/2013-07/pagination-done-the-postgresql-way).
This patch is essentially a hack that caches the count, with the assumption that it does not need to be that accurate anyway. Possible optimizations to this patch include:
=> pagination count cache

lib/travis/honeycomb.rb
when running in unicorn, we have 50 unicorn workers per dyno. currently we are creating 10 honeycomb worker threads per unicorn worker.
this patch makes the pool size configurable, so that we can reduce it to 1 (per unicorn worker).
refs travis-ci/reliability#27
=> honeycomb: make pool size configurable

Gemfile.lock
While testing http_proxy on Enterprise I noticed that the License endpoint in API kept ignoring `no_proxy` and trying to proxy the private address. 
Looking around I found the issue was with Faraday and fixed in 0.13 (https://github.com/lostisland/faraday/pull/712). 
Essentially any code that went `Faraday.new(options).get` would skip setting up the proxy envs correctly. The license code is the only code that I've seen so far that does it. And updating Faraday fixes that in case there are others.
=> Update Faraday to fix issue where it ignores no_proxy in certain cases

Gemfile.lock
Backport of #669 for Enterprise 2.2
=> [Enterprise Backport] Update Faraday to fix issue where it ignores no_proxy in certain cases (#669)

lib/travis/api/v3/queries/builds.rb
the `Travis::API::V3::Services::Active::ForOwner` endpoint currently only considers `created` and `started` jobs. we probably want to expand that to include `queued` and `received` too.
refs travis-ci/reliability#16
=> include queued and received builds in "active" list

spec/spec_helper.rb
The tests ignored `Travis.config.redis` and assumed that Redis runs on `localhost` which is not necessarily true.
There is a second assumption which is that the general Redis is also used for Gatekeeper which is also not necessarily true (they are configured separately), but more likely when running tests.
=> Use Travis.config.redis to empty Redis before each test

lib/travis/api/app/endpoint/authorization.rb, lib/travis/api/v3/services/enterprise_license/find.rb
Backports #684 
We'll also need to do this with 2.1 so that github auth works with proxying/no_proxy.
=> [Enterprise 2.2 Backport] Include base URL in Faraday.new so it honors no_proxy (#684)

spec/lib/travis/config_spec.rb, spec/spec_helper.rb
(and restore the old one afterwards)
All these tests don't play very nicely if you are setting environment variables for setting up, for example, a database or Redis server which are not the default.
* On one hand, they assume the default configuration and an empty environment, so they break if you set something
* On the other hand, some of them overwrite values, which can break your setup for the rest of the tests
The implementation is not super clean, but I couldn't find a way for stubbing the `ENV` constant in mocha, and stubbing the `[]` method won't work because the data could be accessed using other methods like `fetch` (e.g. `Travis::Config` uses `values_at`). I guess using the real environment, as long as we take care of restoring it afterwards, is fine (after all, we were using …
=> Run each test in config_spec in a fresh environment

lib/travis/api/v3/services/repository/activate.rb, lib/travis/services/update_hook.rb
When Enterprise used `travis-pro-api` it always would add keys, even to public repositories. This was because `travis-pro-api` didn't have a concept of public repos. Now that we use `travis-api` we're running into issues where the `source_url` getting passed to the worker is using the non-anonymous GitHub clone URL when we use GitHub Enterprise (https://github.com/travis-ci/travis-api/blob/master/lib/travis/model/repository.rb#L109-L119).
The proper way of fixing this would be to detect if we're using GitHub Enterprise and adjust accordingly. However this has the additional wrinkle of needing to accommodate `Private Mode` on GHE which makes even "Public" repositories require authentication. 
So my approach in this PR is to restore the old behavior of _always_ placing a deploy key when …
=> Always add deploy keys when using travis Enterprise

lib/travis/api/v3/services/repository/activate.rb, lib/travis/services/update_hook.rb
Backports #688 to `enterprise-2.2`.
=> [Enterprise] Backport: Always add deploy keys when using travis Enterprise (#688)

lib/travis/api/v3/billing.rb, lib/travis/api/v3/queries/subscriptions.rb, lib/travis/api/v3/renderer/subscription.rb, lib/travis/api/v3/renderer/subscriptions.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/subscriptions/all.rb, spec/v3/billing_spec.rb, spec/v3/services/subscriptions/all_spec.rb
@tyranja and I paired on this.
This is the endpoint the frontend would request to get all the subscriptions of a user (own and from organizations they belong to), to render the equivalent of this page:
It's work in progress (e.g. we still need to define the attributes that will be in the response) but can be merged if correct.
=> /v3/subscriptions endpoint

lib/travis/api/v3/billing.rb, lib/travis/api/v3/models/subscription.rb, lib/travis/api/v3/queries/subscriptions.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/subscriptions/create.rb, spec/v3/billing_spec.rb, spec/v3/services/subscriptions/all_spec.rb, spec/v3/services/subscriptions/create_spec.rb
(pairing with @tyranja)
This PR reintroduces the `Subscription` model removed in #697 but now as a plain ruby object instead of `ActiveRecord` subclass (no longer database backed). All the implicit stuff query -> service -> renderer seems to be happy with the replacement.
=> POST /v3/subscriptions (creation) endpoint

lib/travis/api/v3/queries/organizations.rb, lib/travis/api/v3/services/organizations/for_current_user.rb, spec/v3/service_index_spec.rb, spec/v3/services/organizations/for_current_user_spec.rb
This commit adds ability to pass a role query param to /orgs requests in
order to filter by role.
=> Allow to filter organizations by role

lib/travis/api/v3/routes.rb, lib/travis/api/v3/routes/dsl.rb, lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
Following the discussion in #690 and a couple of in person conversations too, this PR adds a `hidden_resource` method to the v3 routing DSL, which does the same as `resource` but doesn't show in the service index served at `/`.
The case that this tries to solve is that you can't/shouldn't merge any unfinished API work because it ends up in the generated documentation, and since that's public that makes it difficult to change (because someone might be using it). That's reasonable but leads to long lived branches, late integration, etc.
We are having this problem with `billing-v2` but it seems (according to those conversations) that it's not a new problem.
In some cases (billing can be one) it might even make sense that this is not temporary, and they stay out of the public API (as private …
=> [Proposal-V3] Add a way to hide endpoints from service index

lib/travis/api/v3/routes/dsl.rb, lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
@tyranja and @porras were working on it in their branch `billing-v2`, but I'd like to use it too, so I'm porting it to master.
This basically adds ability to add resources hidden from the service index - useful if we work on features that are not ready for publishing to API users.
=> Add `hidden_resources` method

lib/travis/api/v3/routes/dsl.rb, lib/travis/api/v3/routes/resource.rb, lib/travis/api/v3/service_index.rb, spec/v3/service_index_spec.rb
Sometimes it may be necessary to hide routes from the index, for example
when working on an experimental features. This commit adds a `hide`
method that let's you hide a route.
I went with a kind of a functional approach of `hide(get(:foo))`,
because I didn't want to change too many signatures (ie. adding options
to routes would be more complicated).
=> Allow to hide routes from the index

lib/travis/api/v3/models/subscription.rb, lib/travis/api/v3/renderer/subscription.rb, spec/support/billing_spec_helper.rb, spec/v3/billing_client_spec.rb, spec/v3/services/subscriptions/all_spec.rb, spec/v3/services/subscriptions/create_spec.rb
Instead of exposing those fields as hashes, we parse and then serialize them, so that 1) it's validated (if something's wrong we'll get errors instead of silently rendering potentially badly formatted data) and 2) the generated documentation includes metadata of all exposed data (this I haven't checked but should be the case).
=> Explicity expose billing_info, credit_card_info and owner

lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/model_renderer.rb, lib/travis/api/v3/models/import.rb, lib/travis/api/v3/permissions/generic.rb, lib/travis/api/v3/permissions/organization.rb, lib/travis/api/v3/permissions/user.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/owner/import.rb, lib/travis/config/defaults.rb, spec/v3/services/owner/import_spec.rb
This is the interface for the merge app. In the merge app itself we don't do any checks or authentication, so we need to have an API endpoint that will pass the request to the merge app.
The `import` route and a new permission are hidden from the index, so for now it won't be announced in the docs.
=> Add `/owner/<login>/import` route

lib/travis/api/v3/models/cron.rb
Fix missing repo bug for a cron's branch, recorded here https://sentry.io/travis-ci/org-api-production/issues/504500778/?query=is:unresolved
=> Check if repo exists before checking for github_id

lib/travis/api/app/endpoint/authorization.rb
This backports #684 for `enterprise-2.1`
=> [Enterprise 2.1 Backport] Include base URL in Faraday.new so it honors no_proxy (#684)

lib/travis/api/v3/services/enterprise_license/find.rb
Backports #747 for `enterprise-2.2`
=> [Enterprise Backport] Turn off verification for enterprise license check (#747)

bin/user_mgmt.rb, bin/users
Closes: https://github.com/travis-pro/team-teal/issues/2612 (pardon the private link)
From @danishkhan in that issue: 
------------------------
With only 4 users it's easy to tell how many users there are on the install, but for our customers especially at this stage where it's possible they have more users than they initally purchased a license for it'll be handy for them to see the total count rather than having to count it manually themselves.
Something like
```
ubuntu@ip-10-142-242-227:~$ travis users
anna           Inactive
bnferguson     Active
danishkhan     Active
evildanish     Suspended 2018-03-26
Active: 2 Inactive: 1 Suspended: 1
```
For `--suspended` and `--active`
Having the total will be handy
```
ubuntu@ip-10-142-242-227:~$ travis users --active
bnferguson     Active …
```
=> Update Travis Enterprise User Management to include counts and help

Gemfile.lock
a while back we rewrote [marginalia](https://github.com/travis-ci/marginalia) to hook into the `pg` gem directly instead of using ORMs. a few motivations:
* makes it ORM agnostic, so that it also works with sequel based apps
* removes the query comments from the log-based tracing (since query comments are added under the hood)
* this ensures we are using the same version of marginalia everywhere
=> upgrade marginalia to pg-based version (instead of orm)

lib/travis/api/v3/models/plan.rb, lib/travis/api/v3/models/subscription.rb, lib/travis/api/v3/renderer/plan.rb, spec/support/billing_spec_helper.rb, spec/v3/billing_client_spec.rb, spec/v3/services/subscriptions/all_spec.rb, spec/v3/services/subscriptions/create_spec.rb
This is the reintroduction of #743, which was reverted because the corresponding endpoint in billing-v2 was failing in some circumstances due to old invalid data. This was fixed in travis-pro/billing-v2#75.
I have also added handling for null values in the plan attribute (which is what billing-v2 does now in presence of an invalid plan).
=> Embed Plan representation in Subscription representation

lib/travis/api/v3/models/pull_request.rb, lib/travis/api/v3/models/request.rb
this request: https://developer.travis-ci.org/explore/repo/269284/requests currently returns:
```
{
...
"requests":        [
{
"@type":           "request",
...
"branch_name":     {
"@type":           "branch",
"@href":           "/repo/269284/branch/joshk-changelog",
"@representation": "minimal",
"name":            "..."
},
...
```
but according to the docs it should be a string. this hopefully remedies that!
=> return commit branch name instead of branch object for requests

lib/travis/api/v3/access_control/anonymous.rb, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/access_control/user.rb, lib/travis/api/v3/services/builds/find.rb, lib/travis/api/v3/services/requests/find.rb, lib/travis/model/scope_access.rb, lib/travis/services/base.rb, lib/travis/services/find_builds.rb, lib/travis/services/find_requests.rb
we've been having some issues with slow queries that include checking all repository ids.
an example is:
```
SELECT COUNT(*) FROM "builds" WHERE "builds"."repository_id" = 12345 AND "builds"."event_type" IN ('push', 'api', 'cron') AND (builds.private = false OR builds.repository_id IN (11111, 22222, 12345))
```
the postgres query planner is not smart enough to figure out if the top-level repo id is in the list, it doesn't handle the OR very gracefully.
in the case where we have a repository id, instead of pushing the authentication check down into sql, we can perform it in memory in ruby. we're fetching the list of a user's repo ids already anyway. this makes the queries smaller, the postgres logs less noisy, and the queries potentially more efficient.
for the huge COUNT queries on …
=> perform repository_id access check in ruby when we have a repository_id

lib/travis/config/defaults.rb, lib/travis/sidekiq.rb, spec/lib/travis/config_spec.rb
we no longer connect directly to the logs database from api. this patch makes that explicit by removing the last relics in the code base.
vaguely refs https://github.com/travis-ci/reliability/issues/60
=> remove references to the logs db (we talk to logs over http now)

lib/travis/api/v3/queries/repositories.rb
~Early PR to take advantage of tests DON'T MERGE~
This was causing AR errors when using sort_by=default_branch.last_build
as a filter on /v3/owner/[owner]/repos calls. I'm not convinced this is
a perfect solution, but after an hour of being on org-production I saw
no discernible change in DB load or performance, and it allows the
queries in question to resolve.
Error in sentry:
https://sentry.io/travis-ci/org-api-production/issues/571746986/?query=request_id:d4e62c95-b674-4f17-b967-1df4e70757b7
Issue:
travis-pro/team-teal#2709
=> Prevent sortable on default branches

lib/travis/api/v3/queries/repositories.rb, spec/v3/services/repositories/for_owner_spec.rb
This is a test to see if adding NULLS LAST to the default_branch.last_build helps with the issues loading the org page.
=> Fix sorting of repos on owner/repos endpoint

spec/lib/schedulers/schedule_cron_jobs_spec.rb
While pairing with @rwrede in something else, this test randomly failed on timestamp mismatch. We think that it is because it expects time to be frozen but it's not (`travel` unfreezes it).
Does this fix make sense?
=> Freeze time when travelling

lib/travis/api/v3/billing_client.rb, spec/v3/services/subscriptions/all_spec.rb
Paired with @rwrede.
We added the explanation for this temporary change in a comment:
> because billing-v2 API is changing from responding with an array, to responding with an object where this array is under the `subscriptions` key (in order to add permissions metadata under a separate key), we want to temporarily support both formats
=> Support subscription data both in the toplevel and under a key

lib/travis/api/v3/billing_client.rb, lib/travis/api/v3/models/subscription.rb, lib/travis/api/v3/renderer/subscriptions.rb, spec/v3/billing_client_spec.rb, spec/v3/services/subscriptions/all_spec.rb
With this PR the `/v3/subscriptions` endpoint response gets an extra `@permissions` key with information about whether the current user can create new subscriptions, on a per-owner basis:
```js
{
"@type": "subscriptions",
// ...
"@permissions": [
{ "owner": { "type": "User", "id": 1 }, "create": true },
{ "owner": { "type": "Organization", "id": 1 }, "create": false }
],
"subscriptions": [
{
// ...
}
]
}
```
=>  Expose collection permissions received from billing-v2 

lib/travis/api/v3/models/message.rb, spec/v3/services/messages/for_request_spec.rb
Noticed it wasn't quite right in travis-web. `warning` -> `warn`.
=> Proper warn message type

lib/travis/api/app.rb, lib/travis/api/app/cors.rb, spec/integration/error_handling_spec.rb
We've had lots of issues in the past where once we serve a 5xx page, we would get an error in web that looks like:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.travis-ci.org/blub. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```
Which made it harder to figure out what was even happening. This patch makes it so that we will always include the CORS headers, also in the error case.
Before:
```
➜  ~ curl -v https://api-staging.travis-ci.com -H 'Debug-Err: true'
...
< HTTP/1.1 500 Internal Server Error
< Connection: keep-alive
< Server: nginx
< Date: Fri, 29 Jun 2018 09:44:22 GMT
< Content-Type: text/plain
< Content-Length: 81
< X-Request-Id: 2719549f-4e80-41ee-a003-8411c45252fa
< Via: 1.1 vegur
<
Sorry, we …
```
=> include cors headerss on 5xx error

config/unicorn.rb
We currently signal the `app-initialized` event too early, before the unicorn workers are ready. This makes nginx boot too soon, which starts sending traffic too early resulting in 30 second timeouts as http 500 errors.
By delaying that until the unicorn workers are ready (currently ~30 seconds after the master is), we may be able to delay the overall boot time, and only start receiving traffic once we're ready.
=> Delay app-initialize until unicorn workers are ready

bin/start-nginx, config/nginx.conf.erb
We are not currently using the service times from nginx and they are producing a lot of extra log volume. So it would be good to support turning them off.
We're currently excluding them from papertrail via log filter, but we might as well turn them off at the source. This way they also won't show up in `heroku logs`.
=> reduce nginx log volume

spec/v3/services/builds/for_current_user_spec.rb
When I was going to write a spec for #784, I found that this spec wasn't being run as part of the build (and in fact it was broken since some fields were added to the job representation months ago) because of the file name not ending with `_spec.rb`. This PR fixes this and the spec it self.
Sorry I didn't get to do what I was originally meaning to :sweat_smile:
=> Fix spec and include it in the build

lib/travis/api/v3/models/build.rb, lib/travis/api/v3/models/job.rb, lib/travis/api/v3/models/request.rb, lib/travis/model/build.rb, lib/travis/model/job.rb, lib/travis/model/request.rb
`read_attribute` returns `nil` anyway if the column is missing, but it looks like they are currently still debating if that is a bug or not https://github.com/rails/rails/issues/31017
=> Protect against missing column config on requests, builds, jobs

lib/travis/api/v3/github.rb, lib/travis/github/services/set_hook.rb
This backports #796 to `enterprise-2.2`
@joecorcoran - are there any other places where we need to do this fix or is `travis-api` the only place? 
/cc @acnagy - heads up since you brought up some Enterprise customers already running into this!
=> [Backport] Remove membership event from set hook (#796)

lib/travis/api/app/endpoint/home.rb, spec/unit/default_spec.rb
Follow up to https://github.com/travis-ci/travis-api/pull/802/ it's `enterprise-2.2` backport: https://github.com/travis-ci/travis-api/pull/803
There was one last commit to #802 where we fixed the login issue outlined in: https://github.com/travis-pro/team-teal/issues/2769 (private link, apologies).
=> [Backport] Fix CLI login flow in Enterprise 2.2.2. 

lib/travis/api/v3/models/email_unsubscribe.rb, lib/travis/api/v3/models/repository.rb, lib/travis/api/v3/queries/email_subscription.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/email_subscription/unsubscribe.rb, spec/v3/services/email_subscription/unsubscribe_spec.rb
Adds an endpoint to unsubscribe the currently logged in user from build emails for a single repository:
```
DELETE /repo/123/email_subscription
204 No Content
```
Depends on travis-ci/travis-migrations#137
Fixes travis-pro/team-teal#2776, travis-pro/team-teal#2777
=> Email unsubscribe endpoint

.travis.yml, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/models/json_slice.rb, lib/travis/api/v3/models/json_sync.rb, lib/travis/api/v3/models/preference.rb, lib/travis/api/v3/models/preferences.rb, lib/travis/api/v3/models/user.rb, lib/travis/api/v3/permissions/preferences.rb, lib/travis/api/v3/queries/preference.rb, lib/travis/api/v3/queries/preferences.rb, lib/travis/api/v3/renderer/preference.rb, lib/travis/api/v3/renderer/preferences.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/preference/find.rb, lib/travis/api/v3/services/preference/update.rb, lib/travis/api/v3/services/preferences/for_user.rb, spec/v3/services/preference/find_spec.rb, spec/v3/services/preference/update_spec.rb, spec/v3/services/preferences/for_user_spec.rb
Depends on https://github.com/travis-ci/travis-migrations/pull/138
Adds three new services to API V3, for reading/writing user preferences. The only preference at the moment is `build_emails`, which will toggle whether or not the user receives emails when builds pass/error/fail.
Read all preferences for the authenticated user.
```
curl -H "Authorization: token abc123" \
/v3/preferences
```
```json
{
"@type": "preferences",
"@href": "/v3/preferences",
"@representation": "standard",
"@preferences": [
{
"@type": "preference",
"@href": "/v3/preference/build_emails",
"@representation": "standard",
"name": "build_emails",
"value": true
}
]
}
```
Read one preference for the authenticated user.
```
curl -H "Authorization: token abc123" \
/v3/preference/build_emails
```
```json
{
"@type": …
```
=> Add preferences endpoints

spec/v3/services/log/delete_spec.rb
Updating the dependencies in 5587675706af6df40e9f2f2a60eef5328d55d515 broke the tests because some where specifying a Faraday version. I didn't update but removed this (and other) headers from that stubs, I don't think they were meant to be there.
=> Make spec less brittle by not specifying not essential HTTP headers

lib/travis/api/v3/github.rb
No change of behavior, this should help debugging an exception we're getting from time to time when parsing the hooks data we receive from GitHub, as if it doesn't always has the format we expect.
I fed some garbage (array of arrays instead of array of hashes) in the tests and this is how the exception looks like:
```
Travis::API::V3::GitHub::WebhookError:
Error fetching or parsing Webhook information
Original error: #<TypeError: no implicit conversion of String into Integer>
Hooks data: [["some garbage"]]
```
This can be reverted once we figure out what's going on...
=> Add additional context for exception parsing hook data

lib/travis/api/v3/github.rb, spec/integration/v2/hooks_spec.rb, spec/v3/services/repository/activate_spec.rb, spec/v3/services/repository/deactivate_spec.rb
To avoid problems with renamed repos or users.
The endpoint is not documented but I found online mentions of it (even quoting GitHub about it, e.g.: https://github.com/piotrmurach/github/issues/283) and in fact I think we use it in some other places.
=> Use ids for GitHub API interaction regarding hooks

lib/travis/api/v3/queries/repository.rb, spec/v3/services/repository/find_spec.rb
- Lowercase name and owner on repo slug to allow case-insensitive repo urls
[1250](https://github.com/travis-pro/team-teal/issues/1250)
=> Lowercase owner and name for repo slug

lib/travis/api/v3/access_control/generic.rb
While implementing auth for insights, I found this missing piece that was complicating the implementation, and changed it because it seemed to me to make sense (also, the change broke no tests):
* A user is now `adminable` for themselves. It was already `writable` but this method was missing
=> Make a user `adminable` by the user themselves

lib/travis/api/v3/proxy_service.rb, lib/travis/api/v3/services/insights/insights_proxy.rb, spec/v3/services/insights/metrics_spec.rb
(Builds on top of #856)
Might need additional small changes since this param is still not implemented upstream and might be different (`public`?).
=> Pass the private flag to insights 

lib/travis/api/v3/service.rb, spec/v3/services/build/restart_spec.rb
We started setting the migration_status column on .com repositories as
well, so here we must ensure that we're blocking the API only for the
.org API
=> Don't block API on .com when repo is migrated

lib/travis/api/app/endpoint.rb, spec/integration/v2/builds_spec.rb
We started setting the migration_status column on .com repositories as
well, so here we must ensure that we're blocking the API only for the
.org API
=> Don't block API requests for migrated repo on .com in V2

lib/travis/api/v3/models/repository.rb
When using `Branch.where().first_or_initialize` concurrently there's a
chance of creating branch duplicates. We can't use a unique index on
(repository_id, name) because there are already duplicates in the
branches table, but this commit uses a slightly different approach. A
`unique_name` column has been added to the database that is
automatically populated on insert and update with a value of `name`. A
partial unique index is also set on `(repository_id, unique_name) WHERE
unique_name IS NOT NULL`. Thanks to that we can use "upser" (ie. `INSERT
... ON CONFLICT`).
=> Don't create branch duplicates

lib/travis/api/v3/models/repository.rb, spec/spec_helper.rb
When changing the method to use upsert I missed some things about how it
works, mainly that it checks if a branch returned from
Repository#create_branch is a new record and if it is, a last_build will
be attached there. When using upsert a record will be always fetched
from the database, so I needed to change how the method works.
=> Fix Repository#default_branch method

lib/travis/api/v3/models/repository_migration.rb, spec/v3/services/repository/migrate_spec.rb
github_id is more reliable than slug because it can't change. Slug can
change after a repository transfer, or after renaming a repository or an owner
=> Use github_id for migrating a repository

Gemfile, Gemfile.lock, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/extensions/preferences.rb, lib/travis/api/v3/model.rb, lib/travis/api/v3/models/json_slice.rb, lib/travis/api/v3/models/json_sync.rb, lib/travis/api/v3/models/organization.rb, lib/travis/api/v3/models/organization_preferences.rb, lib/travis/api/v3/models/preferences.rb, lib/travis/api/v3/models/user.rb, lib/travis/api/v3/models/user_preferences.rb, lib/travis/api/v3/queries/preference.rb, lib/travis/api/v3/queries/preferences.rb, lib/travis/api/v3/renderer/preference.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/preference/for_organization.rb, lib/travis/api/v3/services/preference/update.rb, lib/travis/api/v3/services/preferences/for_organization.rb, spec/v3/services/preference/find_spec.rb, spec/v3/services/preference/for_organization_spec.rb, spec/v3/services/preference/update_spec.rb, spec/v3/services/preferences/for_organization_spec.rb, spec/v3/services/preferences/for_user_spec.rb
Based on #871, #872, #873 and #874, and also https://github.com/travis-ci/travis-migrations/pull/166 and https://github.com/travis-ci/travis-migrations/pull/167 (yes the original idea was easier review and deployment, in the end it accumulated a bit :roll_eyes:).
Note: The build is broken because the migration PRs need to get merged first.
Once this is merged it will show up in the API docs, but in the meantime:
Accessing and updating the insights preferences is done similar to how the user's `build_emails` preference is used. The new preference is called `private_insights_visibility` and instead of a boolean it's a string. The accepted values are `'private'` and `'public'` for a user, and `'admins'`, `'members'` and `'public'` for an organization. The URLs are:
* `GET …
=> Render an error when setting an invalid preference

Gemfile, Gemfile.lock, lib/travis/api/v3/access_control/generic.rb, lib/travis/api/v3/extensions/preferences.rb, lib/travis/api/v3/model.rb, lib/travis/api/v3/models/json_slice.rb, lib/travis/api/v3/models/json_sync.rb, lib/travis/api/v3/models/organization.rb, lib/travis/api/v3/models/organization_preferences.rb, lib/travis/api/v3/models/preferences.rb, lib/travis/api/v3/models/user.rb, lib/travis/api/v3/models/user_preferences.rb, lib/travis/api/v3/queries/preference.rb, lib/travis/api/v3/queries/preferences.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services/preferences/for_organization.rb, spec/v3/services/preference/find_spec.rb, spec/v3/services/preference/update_spec.rb, spec/v3/services/preferences/for_organization_spec.rb, spec/v3/services/preferences/for_user_spec.rb
Includes a refactoring I'd like some of you to review: I extracted the wiring of a preferences method to a [_"macro-style"_ class method](https://github.com/travis-ci/travis-api/pull/872/files#diff-1964519b6dd1a6efb1338ffd7d3a058eR5), and did a small change so that all the pieces involved use the [`[]` accessor](https://github.com/travis-ci/travis-api/pull/872/files#diff-1964519b6dd1a6efb1338ffd7d3a058eR7) instead of [calling the method](https://github.com/travis-ci/travis-api/pull/872/files#diff-5db9038dc48b5008aed142437f6148dfL49) (also [here](https://github.com/travis-ci/travis-api/pull/872/files#diff-ab3df38df414689fc3b4d01f7c5868f8L8)), so that the preferences method can have the same name as the column (and it _shadows_ it, disallowing unintended access to the raw data).
Depends on: …
=> Read organizations preferences

lib/travis/api/v3/services/insights/insights_proxy.rb, spec/v3/services/insights/metrics_spec.rb
A `private=true` param can be passed to Insights requests so that results include private insights, otherwise only public insights are returned. Permissions are still taken into account, so if a user without permissions sets the flag, they will only get public insights anyway.
=> Add private flag to insights API

lib/travis/api/v3/renderer/repository.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/repositories/for_current_user_spec.rb, spec/v3/services/repositories/for_owner_spec.rb, spec/v3/services/repository/find_spec.rb
This allows us to display a web UI prompt if we could not migrate
a repo from service hooks to webhooks.
Database values are not yet populated – for now, this is a placeholder attribute that always returns false.
=> Add github_service_hook attr to repos

Rakefile, lib/tasks/enable_repo_migration.rake, lib/travis/api/v3/models/user.rb, lib/travis/api/v3/services/beta_migration_request/create.rb, spec/v3/services/beta_migration_request/create_spec.rb
This PR does the following:
- There is an option to specify how many requests you wish to process. It defaults to 50.
- There is an option to print out debug information, that defaults to false
=> Add rake task to enable migration for opted-in users and other edits

lib/travis/api/v3/github.rb, spec/v3/services/repository/activate_spec.rb, spec/v3/services/repository/deactivate_spec.rb
We've been making patch requests even after the GitHub service hooks
endpoints have been switched off. This removes them.
=> Remove service hooks requests

lib/travis/api/v3/github.rb, spec/v3/services/repository/activate_spec.rb, spec/v3/services/repository/deactivate_spec.rb
This is the backport of https://github.com/travis-ci/travis-api/pull/885 to the `enterprise-2.2` branch. Please let me know if there is a more established way of doing this, this seems like what we have done for backports in the past. 🤷‍♂️
=> [BACKPORT] Allow for insecure SSL when creating or updating webhooks

lib/travis/api/v3/github.rb, spec/v3/services/repository/activate_spec.rb, spec/v3/services/repository/deactivate_spec.rb
The 'Disable SSL Verification' setting (`verify: false`) is already used and passed into Faraday in certain circumstances to allow for use of self-signed certs in traffic between Travis CI components. With this PR the setting will also be used when creating or updating webhooks. 
Without this change the 'Disable SSL Verification' setting in Enterprise effectively doesn't work since Github can't communicate with `travis-listener` and so the request never makes it into our system to begin with.
I will be backporting this change to the `enterprise-2.2` branch but I'm pretty sure that this is worth having in master as well. Willing to chat more about that if anyone disagrees!
P.S. I added @joecorcoran and @porras as reviewers since they were suggested by Github. Please let me know if I should …
=> Allow for insecure SSL when creating or updating webhooks

bin/migrate-hooks
All repos:
```
./bin/migrate-hooks
```
Repos created in one year:
```
./bin/migrate-hooks <year>
```
Needs to be tested, which is hard now that the hooks service for hosted has been taken offline.
https://github.com/travis-ci/product/issues/136
=> Add migrate hooks script for enterprise

lib/travis/api/app/endpoint.rb
We don't really document plain text responses, so I think that whenever
possible, ie. when at least one of the Accept headers allows it, we
should return a JSON response.
=> Return JSON response on error if possible

lib/travis/api/v3/queries/repository.rb, lib/travis/model/repository.rb
This addresses this issue https://github.com/travis-pro/team-teal/issues/2952
and  takes the place of this PR https://github.com/travis-ci/travis-api/pull/908
We still need to update `travis-migrations` to have the index:
```
CREATE INDEX CONCURRENTLY index_repositories_on_lower_owner_name_and_name ON repositories (LOWER(owner_name), LOWER(name)) WHERE invalidated_at IS NULL;
```
=> Update find repo by slug query to handle lowercase

lib/travis/api/v3/models/job.rb, lib/travis/api/v3/queries/log.rb, lib/travis/config/defaults.rb, lib/travis/model/job.rb, lib/travis/remote_log.rb, lib/travis/services/find_log.rb, lib/travis/services/remove_log.rb, spec/integration/v2/jobs_spec.rb, spec/lib/model/job/test_spec.rb, spec/lib/services/find_log_spec.rb, spec/lib/services/update_job_spec.rb, spec/lib/travis/remote_log_spec.rb, spec/unit/endpoint/logs_id_spec.rb, spec/unit/endpoint/logs_spec.rb, spec/v3/services/log/find_spec.rb
When a job is migrated from .org to .com we still want to be able to see logs. We don't want to move logs between S3 buckets, so instead we will request a log from .org logs app or .org bucket when needed.
=> Hit .org logs for migrated jobs

lib/travis/api/app/responders/badge.rb, lib/travis/api/app/responders/image.rb, lib/travis/config/defaults.rb, lib/travis/model/repository.rb, spec/integration/v2/repositories_spec.rb
At the moment most of the READMEs of open source projects and some
services (like cargo, npm etc) point to travis-ci.org as a source of
badges. In order to make it easier to transition this commit changes the
behaviour of badges to redirect some of the badges requests to .com. If
a repo is migrated, a request for a badge will be redirected to .com. If
a repo is not found, a request would also be redirected to .com, which
will ensure that new repos on .com will also be available when using the
.org url.
=> Redirect badges to .com

lib/travis/api/v3.rb, lib/travis/api/v3/services/repository/activate.rb, spec/v3/services/repository/activate_spec.rb
Backporting https://github.com/travis-ci/travis-api/pull/915 in the Enterprise 2.2. branch
=> Enterprise backport #915 return 409 if repo ssh key is missing on repo activate

lib/travis/api/v3/renderer/repository.rb, spec/v3/services/beta_feature/update_spec.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/repositories/for_current_user_spec.rb, spec/v3/services/repositories/for_owner_spec.rb, spec/v3/services/repository/find_spec.rb
This is necessary as part of the Merge work to ensure that we can avoid showing the banner within travis-web notifying users to navigate to org to view their build history after it has been successfully migrated.
=> Add history migration status to standard repository representation

lib/travis/api/v3/queries/builds.rb
After we import the build history from .org to .com we may end up with
id and created_at fields out of sync with numbers. Historically a lower
created_at or id values where always also lower number values. After the
import it's no longer true. That's why we want to change the default
sort value
=> Order builds by number::int DESC by default

lib/travis/api/v3/billing_client.rb, lib/travis/api/v3/queries/subscription.rb, lib/travis/api/v3/services/subscription/cancel.rb, spec/v3/billing_client_spec.rb, spec/v3/services/subscription/cancel_spec.rb
While cancelling a subscription, the api has been updated to pass along additional data related to cancellation reason.
=> added additional params for subscription cancellation

lib/travis/api/v3/models/leads.rb, lib/travis/api/v3/renderer/leads.rb, lib/travis/api/v3/routes.rb, lib/travis/api/v3/services.rb, lib/travis/api/v3/services/leads/create.rb, spec/v3/services/leads/create_spec.rb
The point of this PR is to more closely follow the convention of POSTing to plural endpoints. This is safe to do because right now only an in-development project (travis-web plans page) uses the `/lead` endpoint.
=> Rename lead resource, update endpoint

lib/travis/api/v3/services/leads/create.rb, spec/v3/services/leads/create_spec.rb
For https://travisci.assembla.com/spaces/Web/tickets/220/details
I would like to launch this update just a bit ahead of https://github.com/travis-ci/travis-web/pull/2175. I tested this update against what's currently in production for `travis-web` and it functions fine, it just won't capture the `lead_source` until the 2175 updates are in place on `travis-web`.
=> leads create: add utm fields and lead source

lib/travis/api/v3/services/leads/create.rb
`lead_source` does not exist as a custom field on the production CloseIO account, and I don't have the necessary permissions to create it. So commenting out for now.
=> Fix lead source issue

lib/travis/api/v3/services/leads/create.rb, spec/v3/services/leads/create_spec.rb
I commented out the `lead_source` code because that custom field didn't exist on the production `close` account and it was causing problems. Now Jan added the field, so I'm reintroducing the code for the field. Except that now it's going to be named `referral_source`, at the request of the marketing team. I've also added a check to make sure the field exists before we try to do anything with it.
=> [Plans] Add referral_source

Gemfile, Gemfile.lock, lib/travis/api/attack.rb
This PR aims to fix [this vulnerability](https://github.com/travis-ci/travis-api/network/alert/Gemfile.lock/netaddr/open). It appeared that the version of `netaddr` where the vulnerability is fixed is a complete rewrite of the library and is not backward compatible, so it's impossible to just update. That's why I replaced it with another gem that seems even better to me.
=> Replace netaddr by ipaddress to resolve security vulnerability

lib/travis/api/v3/queries/builds.rb, lib/travis/api/v3/queries/jobs.rb, lib/travis/config/defaults.rb
This avoids hard-coding the timeouts directly in the code and unlocks the ability to experiment without needing to deploy.
=> Make statement timeouts configurable

lib/travis/api/v3/queries/jobs.rb
The current `join` is unbearably slow when no permissions are present.
=> Try improving query times when user has no permissions

.travis.yml
This is just cherry-picked from https://github.com/travis-ci/travis-api/commit/2eb064df96d88b8dbc5b6bbeffd830db9152fb48,
which fixes the issue cropping up in other branches.
=> Port fix for CI

lib/travis/api/app/endpoint/authorization.rb
This allows us to place API at a different subdomain to facilitate deployment of an API Gateway without breaking the current auth flow.
=> Allow us to override auth host via env var

lib/travis/api/v3/query.rb
The `HTTP_ORIGIN` header is not always present. This should fix #1014.
=> Fix missing host

lib/travis/model/job.rb, spec/lib/model/job_spec.rb
Sometimes, when clock is out of sync on different microservices, `finished_at` may be before `started_at` (usually it happens, when build is canceled right away), which results in negative duration. 
We will return 0 in this case.
=> Do not return negative duration

lib/travis/api/app/endpoint/authorization.rb
`#port` is often `nil`:
[10] pry(main)> URI.parse("http://localhost").port
=> 80
[11] pry(main)> Addressable::URI.parse("http://localhost").port
=> nil
[12] pry(main)> Addressable::URI.parse("http://localhost").inferred_port
=> 80
Some URIs will still return `nil`, so we protect against those with `#to_i`.
=> Use `Addressable::URI#inferred_port` for determining port

lib/travis/api/app.rb
Temporary solution disabling ssl redirect for docker env
=> Disable SSL on k8s production env

lib/travis/api/app/endpoint/jobs.rb, lib/travis/api/app/endpoint/logs.rb, lib/travis/api/app/helpers/accept.rb, lib/travis/remote_log.rb, spec/auth/v2.1/jobs_spec.rb, spec/auth/v2.1/logs_spec.rb, spec/auth/v2/jobs_spec.rb, spec/auth/v2/logs_spec.rb, spec/integration/v2/jobs_spec.rb, spec/integration/visibility_spec.rb, spec/lib/travis/remote_log_spec.rb
Once the job logs are archived, they are served from S3 as plain text.
1. Requests with `Accept: application/json` results in 406:
```sh-session
$ curl -H "Accept: application/json" -sSfL https://api.travis-ci.org/jobs/43135435/log
curl: (22) The requested URL returned error: 406 Not Acceptable
```
1. _**unless**_ the `User-Agent` string starts with `Travis`:
<details>
<summary>JSON requests with "User-Agent: Travis foo"</summary>
<pre>
$ curl -H "Accept: application/json" -H "User-Agent: Travis foo" -svSfL https://api.travis-ci.org/jobs/43135435/log
*   Trying 54.243.143.241:443...
* TCP_NODELAY set
* Connected to api.travis-ci.org (54.243.143.241) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: …
=> Serve JSON data for archived job log requests, regardless of the User-Agent value

lib/travis/remote_log.rb
This resulted in internal server error:
$ curl -sSfL -H "Accept: application/json" https://api.travis-ci.org/logs/267373386
curl: (22) The requested URL returned error: 500 Internal Server Error
=> Force UTF-8 when retrieving archived log

lib/travis/api/v3/queries/jobs.rb
PG stops to use indexes when LIMIT is used in SQL query.
The workaround is described here http://datamangling.com/2014/01/17/limit-1-and-performance-in-a-postgres-query/
Columns, which are used in WHERE clause and have indexes should be sorted.
=> jobs endpoint query boost

.travis.yml
Instead of relying on unreliable `CI_NODE_INDEX=0` to decide whether
or not to deploy to Docker Hub, we make use of the existing shipping
logic by simply adding the `branch` condition to the :ship: stage.
=> Remove deployment based on `CI_NODE_INDEX=0`

.travis.yml
this fixes builds on e-2.2 branch (like this: https://travis-ci.com/github/travis-ci/travis-api/jobs/340983030)
=> updated psql to 9.6

lib/travis/api/app/schedulers/schedule_cron_jobs.rb
allow randomization of cron check task sleep time - for specific
envs with multiple cron tasks
=> CRON: interval randomization

lib/travis/api/v3/models/organization.rb, lib/travis/api/v3/permissions/build.rb, lib/travis/api/v3/permissions/generic.rb, lib/travis/api/v3/renderer/owner.rb, spec/v3/services/build/find_spec.rb, spec/v3/services/builds/find_spec.rb, spec/v3/services/builds/for_current_user_spec.rb, spec/v3/services/installation/find_spec.rb, spec/v3/services/organization/find_spec.rb, spec/v3/services/organizations/for_current_user_spec.rb, spec/v3/services/owner/find_spec.rb, spec/v3/services/repositories/for_owner_spec.rb, spec/v3/services/user/current_spec.rb, spec/v3/services/user/find_spec.rb
Checked build priority features for an organisation with below  - 
- User has access to the push permission.
- The build owner (Organization), has access to the priority feature.
And removed "allow_build_priorities" which is added Previously.
=> Build priority feature on an Organization. 

lib/travis/api/v3/permissions/build.rb, lib/travis/api/v3/permissions/job.rb
We have removed this check as it will block in giving a feature in PRD, ie: Show the prioritize button in disabled state when the user is not having push access.
=> Removed push permission for prioritize flag on Build and Job level

lib/travis/api/v3/service_index.rb
In particular, `Queries::Cron` defines two identical sets of
parameters with different prefixes. This results in duplicates in the
ServiceIndex:
$ curl -s -H "Travis-API-Version: 3" -H "Accept: application/json" https://api.travis-ci.com | jq .resources.cron.actions.create[].accepted_params
[
"cron.interval",
"cron.dont_run_if_recent_build_exists",
"cron.interval",
"cron.dont_run_if_recent_build_exists"
]
[
"cron.interval",
"cron.dont_run_if_recent_build_exists",
"cron.interval",
"cron.dont_run_if_recent_build_exists"
]
[
"cron.interval",
"cron.dont_run_if_recent_build_exists",
"cron.interval",
"cron.dont_run_if_recent_build_exists"
]
[
"cron.interval",
"cron.dont_run_if_recent_build_exists",
"cron.interval",
"cron.dont_run_if_recent_build_exists"
]
We avoid this confusion by removing …
=> Remove duplicate parameters from ServiceIndex

lib/travis/api/enqueue/services/restart_model.rb, spec/lib/travis/api/enqueue/services/restart_model_spec.rb, spec/v3/services/job/restart_spec.rb
There is no billing on .ORG so this PR will stop the build restart request from checking if the customer has active plan/subscription.
=> Stop billing requests on org domain

lib/travis/remote_log.rb
Enterprise logs are not stored remotely, the fix fetches the logs from DB
=> Travis CLI fix for enterprise logs

lib/travis/api/v3/models/cron.rb
[TBT-340] - Sentry Error ActiveRecord::RecordNotFound
=> Release 2025 04 22

lib/travis/api/app/endpoint/assembla.rb, lib/travis/remote_vcs/user.rb, lib/travis/services/assembla_user_service.rb, spec/travis/remote_vcs/user_spec.rb, spec/unit/endpoint/assembla_spec.rb
This PR updates the login endpoint to accept a repository_id parameter, which is then passed to travis-vcs to fetch data for the specified repository. When repository_id is provided in the login request, the system forwards this parameter to travis-vcs, enabling targeted repository data fetching instead of processing all repositories
=> Sync only passed space and repository
